import { SIMPLE, narrative } from './helpers'

export const SIMPLE_TREND_TEMPLATES = [
  {
    id: 'bread-price-relief',
    label: 'Bread Price Relief',
    description: 'Food prices stabilize, giving the imperial development party a modest nationwide lift.',
    complexity: SIMPLE,
    family: 'economy',
    scope: ['national'],
    level: 'national',
    party: 'yellow',
    magnitudeRange: [0.08, 0.18],
    tags: ['economy', 'incumbency', 'stability'],
    selectionWeight: 1.4,
    narrative: narrative('The court claims its granaries and trade policy kept bread affordable.', ['stable economy', 'incumbent competence']),
    effects: [{ id: 'national-incumbent-lift', level: 'national', party: 'yellow' }],
  },
  {
    id: 'tax-fatigue',
    label: 'Tax Fatigue',
    description: 'A simple anti-establishment tax mood gives labor organizers a clean opening.',
    complexity: SIMPLE,
    family: 'economy',
    scope: ['national'],
    level: 'national',
    party: 'orange',
    magnitudeRange: [0.08, 0.2],
    tags: ['economy', 'labor', 'anti-establishment'],
    selectionWeight: 1.25,
    narrative: narrative('Voters blame the treasury for taking more than it gives back.', ['tax backlash', 'labor populism']),
    effects: [{ id: 'tax-backlash', level: 'national', party: 'orange' }],
  },
  {
    id: 'academy-breakthrough',
    label: 'Academy Breakthrough',
    description: 'A celebrated scientific breakthrough nudges reform-minded and educated voters toward the civic liberals.',
    complexity: SIMPLE,
    family: 'modernization',
    scope: ['national', 'county'],
    level: 'national',
    party: 'blue',
    magnitudeRange: [0.08, 0.18],
    tags: ['science', 'education', 'reform'],
    selectionWeight: 1.25,
    narrative: narrative('Campus discoveries turn modernization into the campaign language of the week.', ['science boom', 'education politics']),
    effects: [
      { id: 'national-science-bump', level: 'national', party: 'blue', magnitudeFactor: 0.8 },
      {
        id: 'campus-local-bump',
        level: 'county',
        party: 'blue',
        selector: { minIntellectualIndex: 0.55 },
        magnitudeFactor: 1,
        weightBy: { feature: 'intellectual_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
    ],
  },
  {
    id: 'temple-processions',
    label: 'Temple Processions',
    description: 'Localized religious processions lift traditionalists in highly spiritual places.',
    complexity: SIMPLE,
    family: 'religion',
    scope: ['province', 'county'],
    level: 'province',
    party: 'red',
    selector: { minSpiritualIndex: 0.55 },
    magnitudeRange: [0.10, 0.24],
    tags: ['religion', 'traditionalist', 'rural'],
    selectionWeight: 1.25,
    narrative: narrative('Temples and shrines become visible symbols of order and continuity.', ['religious revival', 'traditionalist surge']),
    effects: [
      {
        id: 'spiritual-province-lift',
        level: 'province',
        party: 'red',
        selector: { minSpiritualIndex: 0.55 },
        weightBy: { feature: 'spiritual_index', minMultiplier: 0.85, maxMultiplier: 1.3 },
      },
      {
        id: 'holy-site-county-lift',
        level: 'county',
        party: 'red',
        selector: { minSpiritualIndex: 0.6 },
        magnitudeFactor: 0.8,
        weightBy: { feature: 'spiritual_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
    ],
  },
  {
    id: 'rail-opening',
    label: 'Rail Opening',
    description: 'A new rail corridor rewards the establishment in connected counties.',
    complexity: SIMPLE,
    family: 'infrastructure',
    scope: ['county'],
    level: 'county',
    party: 'yellow',
    selector: { minInfrastructureIndex: 0.65 },
    magnitudeRange: [0.10, 0.24],
    tags: ['infrastructure', 'incumbency', 'development'],
    selectionWeight: 1.35,
    narrative: narrative('Ribbon cuttings and rail access make development feel immediate.', ['rail boom', 'infrastructure politics']),
    effects: [
      {
        id: 'rail-county-lift',
        level: 'county',
        party: 'yellow',
        selector: { minInfrastructureIndex: 0.65 },
        weightBy: { feature: 'infrastructure_index', minMultiplier: 0.9, maxMultiplier: 1.45 },
      },
    ],
  },
  {
    id: 'factory-wage-drive',
    label: 'Factory Wage Drive',
    description: 'Industrial wage organizing gives labor a focused boost in factory and mining districts.',
    complexity: SIMPLE,
    family: 'labor',
    scope: ['county'],
    level: 'county',
    party: 'orange',
    selector: { minIndustrialIndex: 0.55 },
    magnitudeRange: [0.12, 0.28],
    tags: ['labor', 'industrial', 'organizing'],
    selectionWeight: 1.35,
    narrative: narrative('Wage committees spread through workshops, mines, and industrial zones.', ['labor organizing', 'factory politics']),
    effects: [
      {
        id: 'industrial-labor-boost',
        level: 'county',
        party: 'orange',
        selector: { minIndustrialIndex: 0.55 },
        weightBy: { feature: 'worker_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
    ],
  },
  {
    id: 'garrison-parade',
    label: 'Garrison Parade',
    description: 'Military pageantry produces a disciplined traditionalist bump around garrisons.',
    complexity: SIMPLE,
    family: 'security',
    scope: ['county'],
    level: 'county',
    party: 'red',
    selector: { minMilitaryIndex: 0.55 },
    magnitudeRange: [0.12, 0.3],
    tags: ['security', 'military', 'traditionalist'],
    selectionWeight: 1.15,
    narrative: narrative('Garrisons turn patriotic ceremony into a turnout operation.', ['military loyalty', 'security politics']),
    effects: [
      {
        id: 'garrison-red-boost',
        level: 'county',
        party: 'red',
        selector: { minMilitaryIndex: 0.55 },
        weightBy: { feature: 'military_index', minMultiplier: 0.9, maxMultiplier: 1.45 },
      },
    ],
  },
  {
    id: 'market-charter',
    label: 'Market Charter',
    description: 'Merchant associations endorse civic reform in commercial neighborhoods.',
    complexity: SIMPLE,
    family: 'commerce',
    scope: ['county'],
    level: 'county',
    party: 'blue',
    selector: { minCommercialMiddleClassIndex: 0.55 },
    magnitudeRange: [0.10, 0.23],
    tags: ['commerce', 'middle-class', 'reform'],
    selectionWeight: 1.15,
    narrative: narrative('Commercial districts frame reform as competent city management.', ['merchant politics', 'middle class reform']),
    effects: [
      {
        id: 'commercial-blue-boost',
        level: 'county',
        party: 'blue',
        selector: { minCommercialMiddleClassIndex: 0.55 },
        weightBy: { feature: 'commercial_middle_class_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
    ],
  },
  {
    id: 'frontier-petitions',
    label: 'Frontier Petitions',
    description: 'Low-loyalty frontier provinces organize around home-rule petitions.',
    complexity: SIMPLE,
    family: 'autonomy',
    scope: ['province'],
    level: 'province',
    party: 'white',
    selector: { maxLoyaltyIndex: 0.45 },
    magnitudeRange: [0.12, 0.32],
    tags: ['autonomy', 'frontier', 'localist'],
    selectionWeight: 1.2,
    narrative: narrative('Petitions from distant provinces turn discontent into a legal campaign.', ['home rule', 'frontier politics']),
    effects: [
      {
        id: 'low-loyalty-white-boost',
        level: 'province',
        party: 'white',
        selector: { maxLoyaltyIndex: 0.45 },
        weightBy: { feature: 'localist_index', minMultiplier: 0.85, maxMultiplier: 1.45 },
      },
    ],
  },
  {
    id: 'lotus-court-rumors',
    label: 'Lotus Court Rumors',
    description: 'Restorationist rumors travel through Roman and spiritual communities.',
    complexity: SIMPLE,
    family: 'restoration',
    scope: ['province'],
    level: 'province',
    party: 'purple',
    selector: { any: [{ minRomanIdentityIndex: 0.45 }, { minFeatures: { feature: 'restorationist_index', value: 0.55 } }] },
    magnitudeRange: [0.10, 0.26],
    tags: ['restoration', 'roman', 'minority'],
    selectionWeight: 1.1,
    narrative: narrative('A rumored restoration court gives Lotus organizers a story to carry door to door.', ['restorationism', 'Roman identity']),
    effects: [
      {
        id: 'restoration-purple-boost',
        level: 'province',
        party: 'purple',
        selector: { any: [{ minRomanIdentityIndex: 0.45 }, { minFeatures: { feature: 'restorationist_index', value: 0.55 } }] },
        weightBy: { feature: 'restorationist_index', minMultiplier: 0.85, maxMultiplier: 1.5 },
      },
    ],
  },
]
