import { SIMPLE, narrative } from './helpers'

export const SIMPLE_TREND_TEMPLATES = [
  {
    id: 'bread-price-relief',
    label: 'Bread Price Relief',
    description: 'Food prices stabilize, giving the imperial development party a modest nationwide lift.',
    complexity: SIMPLE,
    family: 'economy',
    scope: ['national'],
    level: 'national',
    party: 'yellow',
    magnitudeRange: [0.08, 0.18],
    tags: ['economy', 'incumbency', 'stability'],
    selectionWeight: 1.4,
    narrative: narrative('The court claims its granaries and trade policy kept bread affordable.', ['stable economy', 'incumbent competence']),
    effects: [{ id: 'national-incumbent-lift', level: 'national', party: 'yellow' }],
  },
  {
    id: 'tax-fatigue',
    label: 'Tax Fatigue',
    description: 'A simple anti-establishment tax mood gives labor organizers a clean opening.',
    complexity: SIMPLE,
    family: 'economy',
    scope: ['national'],
    level: 'national',
    party: 'orange',
    magnitudeRange: [0.08, 0.2],
    tags: ['economy', 'labor', 'anti-establishment'],
    selectionWeight: 1.25,
    narrative: narrative('Voters blame the treasury for taking more than it gives back.', ['tax backlash', 'labor populism']),
    effects: [{ id: 'tax-backlash', level: 'national', party: 'orange' }],
  },
  {
    id: 'academy-breakthrough',
    label: 'Academy Breakthrough',
    description: 'A celebrated scientific breakthrough nudges reform-minded and educated voters toward the civic liberals.',
    complexity: SIMPLE,
    family: 'modernization',
    scope: ['national', 'county'],
    level: 'national',
    party: 'blue',
    magnitudeRange: [0.08, 0.18],
    tags: ['science', 'education', 'reform'],
    selectionWeight: 1.25,
    narrative: narrative('Campus discoveries turn modernization into the campaign language of the week.', ['science boom', 'education politics']),
    effects: [
      { id: 'national-science-bump', level: 'national', party: 'blue', magnitudeFactor: 0.8 },
      {
        id: 'campus-local-bump',
        level: 'county',
        party: 'blue',
        selector: { minIntellectualIndex: 0.55 },
        magnitudeFactor: 1,
        weightBy: { feature: 'intellectual_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
    ],
  },
  {
    id: 'temple-processions',
    label: 'Temple Processions',
    description: 'Localized religious processions lift traditionalists in highly spiritual places.',
    complexity: SIMPLE,
    family: 'religion',
    scope: ['province', 'county'],
    level: 'province',
    party: 'red',
    selector: { minSpiritualIndex: 0.55 },
    magnitudeRange: [0.10, 0.24],
    tags: ['religion', 'traditionalist', 'rural'],
    selectionWeight: 1.25,
    narrative: narrative('Temples and shrines become visible symbols of order and continuity.', ['religious revival', 'traditionalist surge']),
    effects: [
      {
        id: 'spiritual-province-lift',
        level: 'province',
        party: 'red',
        selector: { minSpiritualIndex: 0.55 },
        weightBy: { feature: 'spiritual_index', minMultiplier: 0.85, maxMultiplier: 1.3 },
      },
      {
        id: 'holy-site-county-lift',
        level: 'county',
        party: 'red',
        selector: { minSpiritualIndex: 0.6 },
        magnitudeFactor: 0.8,
        weightBy: { feature: 'spiritual_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
    ],
  },
  {
    id: 'rail-opening',
    label: 'Rail Opening',
    description: 'A new rail corridor rewards the establishment in connected counties.',
    complexity: SIMPLE,
    family: 'infrastructure',
    scope: ['county'],
    level: 'county',
    party: 'yellow',
    selector: { minInfrastructureIndex: 0.65 },
    magnitudeRange: [0.10, 0.24],
    tags: ['infrastructure', 'incumbency', 'development'],
    selectionWeight: 1.35,
    narrative: narrative('Ribbon cuttings and rail access make development feel immediate.', ['rail boom', 'infrastructure politics']),
    effects: [
      {
        id: 'rail-county-lift',
        level: 'county',
        party: 'yellow',
        selector: { minInfrastructureIndex: 0.65 },
        weightBy: { feature: 'infrastructure_index', minMultiplier: 0.9, maxMultiplier: 1.45 },
      },
    ],
  },
  {
    id: 'factory-wage-drive',
    label: 'Factory Wage Drive',
    description: 'Industrial wage organizing gives labor a focused boost in factory and mining districts.',
    complexity: SIMPLE,
    family: 'labor',
    scope: ['county'],
    level: 'county',
    party: 'orange',
    selector: { minIndustrialIndex: 0.55 },
    magnitudeRange: [0.12, 0.28],
    tags: ['labor', 'industrial', 'organizing'],
    selectionWeight: 1.35,
    narrative: narrative('Wage committees spread through workshops, mines, and industrial zones.', ['labor organizing', 'factory politics']),
    effects: [
      {
        id: 'industrial-labor-boost',
        level: 'county',
        party: 'orange',
        selector: { minIndustrialIndex: 0.55 },
        weightBy: { feature: 'worker_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
    ],
  },
  {
    id: 'garrison-parade',
    label: 'Garrison Parade',
    description: 'Military pageantry produces a disciplined traditionalist bump around garrisons.',
    complexity: SIMPLE,
    family: 'security',
    scope: ['county'],
    level: 'county',
    party: 'red',
    selector: { minMilitaryIndex: 0.55 },
    magnitudeRange: [0.12, 0.3],
    tags: ['security', 'military', 'traditionalist'],
    selectionWeight: 1.15,
    narrative: narrative('Garrisons turn patriotic ceremony into a turnout operation.', ['military loyalty', 'security politics']),
    effects: [
      {
        id: 'garrison-red-boost',
        level: 'county',
        party: 'red',
        selector: { minMilitaryIndex: 0.55 },
        weightBy: { feature: 'military_index', minMultiplier: 0.9, maxMultiplier: 1.45 },
      },
    ],
  },
  {
    id: 'market-charter',
    label: 'Market Charter',
    description: 'Merchant associations endorse civic reform in commercial neighborhoods.',
    complexity: SIMPLE,
    family: 'commerce',
    scope: ['county'],
    level: 'county',
    party: 'blue',
    selector: { minCommercialMiddleClassIndex: 0.55 },
    magnitudeRange: [0.10, 0.23],
    tags: ['commerce', 'middle-class', 'reform'],
    selectionWeight: 1.15,
    narrative: narrative('Commercial districts frame reform as competent city management.', ['merchant politics', 'middle class reform']),
    effects: [
      {
        id: 'commercial-blue-boost',
        level: 'county',
        party: 'blue',
        selector: { minCommercialMiddleClassIndex: 0.55 },
        weightBy: { feature: 'commercial_middle_class_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
    ],
  },
  {
    id: 'frontier-petitions',
    label: 'Frontier Petitions',
    description: 'Low-loyalty frontier provinces organize around home-rule petitions.',
    complexity: SIMPLE,
    family: 'autonomy',
    scope: ['province'],
    level: 'province',
    party: 'white',
    selector: { maxLoyaltyIndex: 0.45 },
    magnitudeRange: [0.12, 0.32],
    tags: ['autonomy', 'frontier', 'localist'],
    selectionWeight: 1.2,
    narrative: narrative('Petitions from distant provinces turn discontent into a legal campaign.', ['home rule', 'frontier politics']),
    effects: [
      {
        id: 'low-loyalty-white-boost',
        level: 'province',
        party: 'white',
        selector: { maxLoyaltyIndex: 0.45 },
        weightBy: { feature: 'localist_index', minMultiplier: 0.85, maxMultiplier: 1.45 },
      },
    ],
  },
  {
    id: 'lotus-court-rumors',
    label: 'Lotus Court Rumors',
    description: 'Restorationist rumors travel through Roman and spiritual communities.',
    complexity: SIMPLE,
    family: 'restoration',
    scope: ['province'],
    level: 'province',
    party: 'purple',
    selector: { any: [{ minRomanIdentityIndex: 0.45 }, { minFeatures: { feature: 'restorationist_index', value: 0.55 } }] },
    magnitudeRange: [0.10, 0.26],
    tags: ['restoration', 'roman', 'minority'],
    selectionWeight: 1.1,
    narrative: narrative('A rumored restoration court gives Lotus organizers a story to carry door to door.', ['restorationism', 'Roman identity']),
    effects: [
      {
        id: 'restoration-purple-boost',
        level: 'province',
        party: 'purple',
        selector: { any: [{ minRomanIdentityIndex: 0.45 }, { minFeatures: { feature: 'restorationist_index', value: 0.55 } }] },
        weightBy: { feature: 'restorationist_index', minMultiplier: 0.85, maxMultiplier: 1.5 },
      },
    ],
  },
  {
    id: 'harvest-festival',
    label: 'Harvest Festival',
    description: 'A good harvest season softens rural anger and gives traditionalists a quiet countryside lift.',
    complexity: SIMPLE,
    family: 'rural',
    scope: ['province', 'county'],
    level: 'county',
    party: 'red',
    selector: { minAgrarianIndex: 0.5 },
    magnitudeRange: [0.06, 0.16],
    tags: ['rural', 'stability', 'traditionalist', 'calming'],
    selectionWeight: 1.25,
    narrative: narrative('Harvest fairs and temple meals turn politics toward gratitude and continuity.', ['good harvest', 'rural calm']),
    effects: [
      {
        id: 'agrarian-red-calm',
        level: 'county',
        party: 'red',
        selector: { minAgrarianIndex: 0.5 },
        weightBy: { feature: 'agrarian_index', minMultiplier: 0.85, maxMultiplier: 1.25 },
      },
      {
        id: 'food-province-yellow-calm',
        level: 'province',
        party: 'yellow',
        selector: { minFeatures: { feature: 'food_index', value: 0.55 } },
        magnitudeFactor: 0.45,
        weightBy: { feature: 'food_index', minMultiplier: 0.85, maxMultiplier: 1.2 },
      },
    ],
  },
  {
    id: 'quiet-budget-surplus',
    label: 'Quiet Budget Surplus',
    description: 'A small, unflashy treasury surplus reassures loyal provinces without creating a wave.',
    complexity: SIMPLE,
    family: 'governance',
    scope: ['national', 'province'],
    level: 'national',
    party: 'yellow',
    magnitudeRange: [0.05, 0.14],
    tags: ['governance', 'stability', 'incumbency', 'calming'],
    selectionWeight: 1.2,
    narrative: narrative('The government has no grand promise, just enough margin to look competent.', ['budget calm', 'administrative competence']),
    effects: [
      { id: 'national-yellow-budget-calm', level: 'national', party: 'yellow', magnitudeFactor: 0.65 },
      {
        id: 'loyal-province-yellow-budget',
        level: 'province',
        party: 'yellow',
        selector: { minLoyaltyIndex: 0.6 },
        magnitudeFactor: 0.75,
        weightBy: { feature: 'loyalty_index', minMultiplier: 0.85, maxMultiplier: 1.25 },
      },
    ],
  },
  {
    id: 'courthouse-mediation',
    label: 'Courthouse Mediation',
    description: 'Local courts and civic elders defuse a set of provincial disputes, helping institutional reformers.',
    complexity: SIMPLE,
    family: 'governance',
    scope: ['province', 'county'],
    level: 'province',
    party: 'blue',
    selector: { any: [{ minIntellectualIndex: 0.45 }, { minLocalistIndex: 0.45 }] },
    magnitudeRange: [0.06, 0.17],
    tags: ['governance', 'reform', 'localism', 'calming'],
    selectionWeight: 1.15,
    narrative: narrative('Mediators, clerks, and local jurists make institutional politics feel useful.', ['civic mediation', 'quiet reform']),
    effects: [
      {
        id: 'province-blue-mediation',
        level: 'province',
        party: 'blue',
        selector: { any: [{ minIntellectualIndex: 0.45 }, { minLocalistIndex: 0.45 }] },
        weightBy: [
          { feature: 'intellectual_index', minMultiplier: 0.85, maxMultiplier: 1.2 },
          { feature: 'localist_index', minMultiplier: 0.9, maxMultiplier: 1.2 },
        ],
      },
      {
        id: 'worker-grievance-mediation-drag',
        level: 'county',
        party: 'orange',
        mode: 'suppress',
        selector: { minWorkerGrievanceIndex: 0.45 },
        magnitudeFactor: 0.35,
      },
    ],
  },
  {
    id: 'river-ferry-restored',
    label: 'River Ferry Restored',
    description: 'Small transport repairs make connected counties a little more patient with the establishment.',
    complexity: SIMPLE,
    family: 'infrastructure',
    scope: ['county'],
    level: 'county',
    party: 'yellow',
    selector: { minInfrastructureIndex: 0.45 },
    magnitudeRange: [0.07, 0.18],
    tags: ['infrastructure', 'development', 'stability', 'calming'],
    selectionWeight: 1.25,
    narrative: narrative('Ferries, crossings, and depot repairs make government competence tangible.', ['routine infrastructure', 'transport repairs']),
    effects: [
      {
        id: 'modest-infrastructure-yellow',
        level: 'county',
        party: 'yellow',
        selector: { minInfrastructureIndex: 0.45 },
        weightBy: { feature: 'infrastructure_index', minMultiplier: 0.85, maxMultiplier: 1.3 },
      },
    ],
  },
  {
    id: 'guild-apprenticeship-fair',
    label: 'Guild Apprenticeship Fair',
    description: 'Apprenticeship fairs bridge shops, workshops, and schools in commercially mixed counties.',
    complexity: SIMPLE,
    family: 'labor',
    scope: ['county'],
    level: 'county',
    party: 'blue',
    selector: { any: [{ minCommercialMiddleClassIndex: 0.5 }, { minIndustrialIndex: 0.45 }] },
    magnitudeRange: [0.07, 0.18],
    tags: ['labor', 'commerce', 'education', 'calming'],
    selectionWeight: 1.15,
    narrative: narrative('Guild halls pitch skills and orderly advancement instead of confrontation.', ['apprenticeships', 'skills politics']),
    effects: [
      {
        id: 'apprenticeship-blue-county',
        level: 'county',
        party: 'blue',
        selector: { minCommercialMiddleClassIndex: 0.5 },
        weightBy: { feature: 'commercial_middle_class_index', minMultiplier: 0.85, maxMultiplier: 1.25 },
      },
      {
        id: 'apprenticeship-orange-worker',
        level: 'county',
        party: 'orange',
        selector: { minIndustrialIndex: 0.45 },
        magnitudeFactor: 0.55,
        weightBy: { feature: 'worker_index', minMultiplier: 0.85, maxMultiplier: 1.2 },
      },
    ],
  },
  {
    id: 'shrine-repair-fund',
    label: 'Shrine Repair Fund',
    description: 'A modest fund for old shrines reassures spiritual counties and softens restorationist edges.',
    complexity: SIMPLE,
    family: 'religion',
    scope: ['province', 'county'],
    level: 'county',
    party: 'red',
    selector: { minSpiritualIndex: 0.5 },
    magnitudeRange: [0.07, 0.18],
    tags: ['religion', 'traditionalist', 'restoration', 'calming'],
    selectionWeight: 1.1,
    narrative: narrative('Repair grants make continuity feel practical rather than incendiary.', ['shrine repairs', 'religious calm']),
    effects: [
      {
        id: 'shrine-red-calm',
        level: 'county',
        party: 'red',
        selector: { minSpiritualIndex: 0.5 },
        weightBy: { feature: 'spiritual_index', minMultiplier: 0.85, maxMultiplier: 1.25 },
      },
      {
        id: 'restoration-purple-softened',
        level: 'province',
        party: 'purple',
        mode: 'suppress',
        selector: { minFeatures: { feature: 'restorationist_index', value: 0.55 } },
        magnitudeFactor: 0.3,
      },
    ],
  },
  {
    id: 'neighborhood-watch-pact',
    label: 'Neighborhood Watch Pact',
    description: 'Local safety committees give security voters a small lift without a national emergency.',
    complexity: SIMPLE,
    family: 'security',
    scope: ['county'],
    level: 'county',
    party: 'red',
    selector: { any: [{ minMilitaryIndex: 0.35 }, { minFeatures: { feature: 'urban_index', value: 0.55 } }] },
    magnitudeRange: [0.07, 0.19],
    tags: ['security', 'localism', 'stability', 'calming'],
    selectionWeight: 1.05,
    narrative: narrative('Watch captains and ward elders make order feel local, not imperial.', ['local safety', 'neighborhood order']),
    effects: [
      {
        id: 'urban-watch-red',
        level: 'county',
        party: 'red',
        selector: { any: [{ minMilitaryIndex: 0.35 }, { minFeatures: { feature: 'urban_index', value: 0.55 } }] },
        weightBy: [
          { feature: 'military_index', minMultiplier: 0.85, maxMultiplier: 1.2 },
          { feature: 'urban_index', minMultiplier: 0.85, maxMultiplier: 1.2 },
        ],
      },
    ],
  },
  {
    id: 'seasonal-work-credit',
    label: 'Seasonal Work Credit',
    description: 'A predictable work-credit program gives labor a modest, practical argument in rural and industrial places.',
    complexity: SIMPLE,
    family: 'labor',
    scope: ['province', 'county'],
    level: 'county',
    party: 'orange',
    selector: { any: [{ minWorkerGrievanceIndex: 0.4 }, { minAgrarianIndex: 0.5 }] },
    magnitudeRange: [0.08, 0.19],
    tags: ['labor', 'rural', 'economy', 'calming'],
    selectionWeight: 1.2,
    narrative: narrative('Work credits turn class politics into a practical seasonal bargain.', ['work credits', 'seasonal labor']),
    effects: [
      {
        id: 'seasonal-orange-workers',
        level: 'county',
        party: 'orange',
        selector: { any: [{ minWorkerGrievanceIndex: 0.4 }, { minAgrarianIndex: 0.5 }] },
        weightBy: { feature: 'worker_grievance_index', fallbackKeys: ['worker_index', 'agrarian_index'], minMultiplier: 0.85, maxMultiplier: 1.3 },
      },
    ],
  },
  {
    id: 'minority-language-circular',
    label: 'Minority Language Circular',
    description: 'A quiet language-access order reassures minority and localist communities.',
    complexity: SIMPLE,
    family: 'minority',
    scope: ['province', 'county'],
    level: 'province',
    party: 'purple',
    selector: { any: [{ minFeatures: { feature: 'minority_religion_share', value: 0.35 } }, { minLocalistIndex: 0.5 }] },
    magnitudeRange: [0.07, 0.18],
    tags: ['minority', 'localism', 'reform', 'calming'],
    selectionWeight: 1.05,
    narrative: narrative('Translation orders and local notices make marginal communities feel seen.', ['language access', 'minority reassurance']),
    effects: [
      {
        id: 'minority-purple-language',
        level: 'province',
        party: 'purple',
        selector: { minFeatures: { feature: 'minority_religion_share', value: 0.35 } },
        weightBy: { feature: 'minority_religion_share', minMultiplier: 0.85, maxMultiplier: 1.25 },
      },
      {
        id: 'localist-white-language',
        level: 'province',
        party: 'white',
        selector: { minLocalistIndex: 0.5 },
        magnitudeFactor: 0.6,
        weightBy: { feature: 'localist_index', minMultiplier: 0.85, maxMultiplier: 1.25 },
      },
    ],
  },
  {
    id: 'port-market-week',
    label: 'Port Market Week',
    description: 'Merchant festivals and open markets lift reformers in commercial districts.',
    complexity: SIMPLE,
    family: 'commerce',
    scope: ['county'],
    level: 'county',
    party: 'blue',
    selector: { minCommercialMiddleClassIndex: 0.5 },
    magnitudeRange: [0.08, 0.2],
    tags: ['commerce', 'reform', 'middle-class', 'calming'],
    selectionWeight: 1.15,
    narrative: narrative('Market-week politics makes reform sound like competent trade management.', ['market week', 'merchant confidence']),
    effects: [
      {
        id: 'commercial-blue-market-week',
        level: 'county',
        party: 'blue',
        selector: { minCommercialMiddleClassIndex: 0.5 },
        weightBy: { feature: 'commercial_middle_class_index', minMultiplier: 0.85, maxMultiplier: 1.3 },
      },
      {
        id: 'yellow-trade-incumbent-echo',
        level: 'county',
        party: 'yellow',
        selector: { minInfrastructureIndex: 0.55 },
        magnitudeFactor: 0.35,
      },
    ],
  },
  // --- BUILDING BLOCK TRENDS (Generic Moods) ---
  {
    id: 'consumer-optimism',
    label: 'Consumer Optimism',
    description: 'A general sense of economic well-being lifts the establishment and commercial centers.',
    complexity: SIMPLE,
    family: 'economy',
    scope: ['national', 'county'],
    level: 'national',
    party: 'yellow',
    magnitudeRange: [0.05, 0.12],
    tags: ['economy', 'stability', 'incumbency'],
    selectionWeight: 1.5,
    narrative: narrative('People feel the future is stable, giving the court a quiet vote of confidence.', ['optimism', 'economic calm']),
    effects: [
      { id: 'national-optimism-yellow', level: 'national', party: 'yellow' },
      { id: 'commercial-optimism-blue', level: 'county', party: 'blue', selector: { minCommercialMiddleClassIndex: 0.5 }, magnitudeFactor: 0.6 },
    ],
  },
  {
    id: 'urban-youth-pulse',
    label: 'Urban Youth Pulse',
    description: 'A restless mood among city youth gives challengers a slight energetic lift.',
    complexity: SIMPLE,
    family: 'social',
    scope: ['county'],
    level: 'county',
    party: 'orange',
    selector: { minFeatures: { feature: 'urban_index', value: 0.55 } },
    magnitudeRange: [0.08, 0.18],
    tags: ['social', 'urban', 'anti-establishment'],
    selectionWeight: 1.4,
    narrative: narrative('Coffee houses and university squares hum with a desire for change.', ['urban energy', 'youth restlessness']),
    effects: [
      { id: 'urban-orange-pulse', level: 'county', party: 'orange', selector: { minFeatures: { feature: 'urban_index', value: 0.55 } } },
      { id: 'urban-blue-pulse', level: 'county', party: 'blue', selector: { minIntellectualIndex: 0.5 }, magnitudeFactor: 0.5 },
    ],
  },
  {
    id: 'rural-traditionalist-pulse',
    label: 'Rural Traditionalist Pulse',
    description: 'A steady, quiet mood of continuity in the countryside reinforces traditionalist loyalties.',
    complexity: SIMPLE,
    family: 'social',
    scope: ['county'],
    level: 'county',
    party: 'red',
    selector: { minAgrarianIndex: 0.55 },
    magnitudeRange: [0.06, 0.14],
    tags: ['social', 'rural', 'stability'],
    selectionWeight: 1.4,
    narrative: narrative('In the villages, the cycle of seasons remains the primary political compass.', ['rural continuity', 'traditionalist steady']),
    effects: [
      { id: 'rural-red-pulse', level: 'county', party: 'red', selector: { minAgrarianIndex: 0.55 } },
    ],
  },
  {
    id: 'administrative-efficiency',
    label: 'Administrative Efficiency',
    description: 'Competent, boring government makes the establishment look reliable.',
    complexity: SIMPLE,
    family: 'governance',
    scope: ['national', 'province'],
    level: 'national',
    party: 'yellow',
    magnitudeRange: [0.05, 0.12],
    tags: ['governance', 'stability', 'incumbency'],
    selectionWeight: 1.3,
    narrative: narrative('Nothing major is broken, which is often the best argument for the status quo.', ['competence', 'boring governance']),
    effects: [
      { id: 'national-efficiency-yellow', level: 'national', party: 'yellow' },
      { id: 'loyal-province-yellow', level: 'province', party: 'yellow', selector: { minLoyaltyIndex: 0.6 }, magnitudeFactor: 0.5 },
    ],
  },
  {
    id: 'bureaucratic-friction',
    label: 'Bureaucratic Friction',
    description: 'Annoying red tape and slow processes irritate the public and local leaders.',
    complexity: SIMPLE,
    family: 'governance',
    scope: ['national', 'province'],
    level: 'province',
    party: 'white',
    magnitudeRange: [0.07, 0.16],
    tags: ['governance', 'grievance', 'localism'],
    selectionWeight: 1.2,
    narrative: narrative('Slow clerks and complex forms turn administrative boredom into political irritation.', ['red tape', 'bureaucratic drag']),
    effects: [
      { id: 'province-white-friction', level: 'province', party: 'white' },
      { id: 'worker-orange-friction', level: 'county', party: 'orange', selector: { minWorkerGrievanceIndex: 0.4 }, magnitudeFactor: 0.5 },
    ],
  },
  {
    id: 'cultural-pride-surge',
    label: 'Cultural Pride Surge',
    description: 'A non-political surge in local cultural pride reinforces regional identity.',
    complexity: SIMPLE,
    family: 'identity',
    scope: ['province'],
    level: 'province',
    party: 'white',
    magnitudeRange: [0.08, 0.2],
    tags: ['identity', 'localism', 'culture'],
    selectionWeight: 1.3,
    narrative: narrative('Local festivals and rediscovered traditions make people think of home first.', ['cultural surge', 'regional pride']),
    effects: [
      { id: 'province-white-pride', level: 'province', party: 'white', weightBy: { feature: 'localist_index', minMultiplier: 0.9, maxMultiplier: 1.4 } },
      { id: 'province-purple-pride', level: 'province', party: 'purple', selector: { minRomanIdentityIndex: 0.4 }, magnitudeFactor: 0.6 },
    ],
  },
  {
    id: 'dockworker-slowdown',
    label: 'Dockworker Slowdown',
    description: 'Port delays and shipping grievances give labor organizers leverage in maritime counties.',
    complexity: SIMPLE,
    family: 'labor',
    scope: ['county'],
    level: 'county',
    party: 'orange',
    selector: { any: [{ minMaritimeIndex: 0.5 }, { minIndustrialIndex: 0.45 }] },
    magnitudeRange: [0.08, 0.22],
    tags: ['labor', 'maritime', 'commerce', 'grievance'],
    selectionWeight: 1.15,
    narrative: narrative('Dock schedules, harbor wages, and delayed cargo become campaign language.', ['dockworker slowdown', 'port labor']),
    effects: [
      {
        id: 'maritime-orange-slowdown',
        level: 'county',
        party: 'orange',
        selector: { any: [{ minMaritimeIndex: 0.5 }, { minIndustrialIndex: 0.45 }] },
        weightBy: [
          { feature: 'maritime_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
          { feature: 'worker_index', minMultiplier: 0.85, maxMultiplier: 1.25 },
        ],
      },
      {
        id: 'port-incumbent-friction',
        level: 'county',
        party: 'yellow',
        mode: 'suppress',
        selector: { minMaritimeIndex: 0.5 },
        magnitudeFactor: 0.3,
      },
    ],
  },
  {
    id: 'scholarship-expansion',
    label: 'Scholarship Expansion',
    description: 'Education grants turn campus and professional counties toward reform-minded modernizers.',
    complexity: SIMPLE,
    family: 'modernization',
    scope: ['county', 'national'],
    level: 'county',
    party: 'blue',
    selector: { any: [{ minIntellectualIndex: 0.45 }, { minCulturalEliteIndex: 0.45 }] },
    magnitudeRange: [0.07, 0.19],
    tags: ['education', 'science', 'reform', 'modernization'],
    selectionWeight: 1.2,
    narrative: narrative('Scholarship rolls make reform politics personal to students and families.', ['scholarships', 'education grants']),
    effects: [
      {
        id: 'campus-blue-scholarships',
        level: 'county',
        party: 'blue',
        selector: { any: [{ minIntellectualIndex: 0.45 }, { minCulturalEliteIndex: 0.45 }] },
        weightBy: { feature: 'intellectual_index', fallbackKeys: ['cultural_elite_index'], minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
      {
        id: 'national-education-blue',
        level: 'national',
        party: 'blue',
        magnitudeFactor: 0.35,
      },
    ],
  },
  {
    id: 'veteran-pension-delay',
    label: 'Veteran Pension Delay',
    description: 'Delayed benefits anger garrison communities and split security voters away from the establishment.',
    complexity: SIMPLE,
    family: 'security',
    scope: ['county', 'province'],
    level: 'county',
    party: 'red',
    selector: { minMilitaryIndex: 0.4 },
    magnitudeRange: [0.08, 0.21],
    tags: ['security', 'military', 'grievance', 'anti-establishment'],
    selectionWeight: 1.1,
    narrative: narrative('Veterans ask why loyalty is praised faster than pensions are paid.', ['veteran benefits', 'pension delay']),
    effects: [
      {
        id: 'veteran-red-benefit-anger',
        level: 'county',
        party: 'red',
        selector: { minMilitaryIndex: 0.4 },
        weightBy: { feature: 'military_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
      {
        id: 'garrison-yellow-benefit-drag',
        level: 'county',
        party: 'yellow',
        mode: 'suppress',
        selector: { minMilitaryIndex: 0.4 },
        magnitudeFactor: 0.35,
      },
    ],
  },
  {
    id: 'pilgrim-road-campaign',
    label: 'Pilgrim Road Campaign',
    description: 'Repairs to shrine roads blend religious continuity with practical infrastructure politics.',
    complexity: SIMPLE,
    family: 'religion',
    scope: ['county', 'province'],
    level: 'county',
    party: 'red',
    selector: { all: [{ minSpiritualIndex: 0.45 }, { minInfrastructureIndex: 0.35 }] },
    magnitudeRange: [0.07, 0.18],
    tags: ['religion', 'infrastructure', 'traditionalist', 'stability'],
    selectionWeight: 1.05,
    narrative: narrative('Pilgrims notice which roads are passable and which officials showed up.', ['pilgrim roads', 'shrine access']),
    effects: [
      {
        id: 'pilgrim-red-road-lift',
        level: 'county',
        party: 'red',
        selector: { all: [{ minSpiritualIndex: 0.45 }, { minInfrastructureIndex: 0.35 }] },
        weightBy: [
          { feature: 'spiritual_index', minMultiplier: 0.85, maxMultiplier: 1.25 },
          { feature: 'infrastructure_index', minMultiplier: 0.85, maxMultiplier: 1.2 },
        ],
      },
      {
        id: 'pilgrim-yellow-competence-echo',
        level: 'county',
        party: 'yellow',
        selector: { minInfrastructureIndex: 0.55 },
        magnitudeFactor: 0.35,
      },
    ],
  },
  // --- NEW SIMPLE TRENDS: Using new features from normalization update ---
  {
    id: 'development-showcase',
    label: 'Development Showcase',
    description: 'Highly developed provinces highlight their infrastructure and culture, benefiting reformers.',
    complexity: SIMPLE,
    family: 'modernization',
    scope: ['province', 'county'],
    level: 'province',
    party: 'blue',
    selector: { minFeatures: { feature: 'development_index', value: 0.55 } },
    magnitudeRange: [0.08, 0.2],
    tags: ['modernization', 'development', 'reform'],
    selectionWeight: 1.15,
    narrative: narrative('Developed regions showcase their progress as a model for the empire.', ['development showcase', 'progressive example']),
    effects: [
      {
        id: 'developed-blue-showcase',
        level: 'province',
        party: 'blue',
        selector: { minFeatures: { feature: 'development_index', value: 0.55 } },
        weightBy: { feature: 'development_index', minMultiplier: 0.85, maxMultiplier: 1.4 },
      },
    ],
  },
  {
    id: 'diverse-economy-coalition',
    label: 'Diverse Economy Coalition',
    description: 'Provinces with diverse economies find common ground across sectoral divides.',
    complexity: SIMPLE,
    family: 'economy',
    scope: ['province', 'county'],
    level: 'county',
    party: 'orange',
    selector: { minFeatures: { feature: 'economic_diversity_index', value: 0.45 } },
    magnitudeRange: [0.09, 0.22],
    tags: ['economy', 'labor', 'diversity'],
    selectionWeight: 1.1,
    narrative: narrative('Economic diversity creates unexpected alliances among workers.', ['diverse economy', 'cross-sector solidarity']),
    effects: [
      {
        id: 'diverse-orange-coalition',
        level: 'county',
        party: 'orange',
        selector: { minFeatures: { feature: 'economic_diversity_index', value: 0.45 } },
        weightBy: { feature: 'economic_diversity_index', minMultiplier: 0.85, maxMultiplier: 1.45 },
      },
    ],
  },
  {
    id: 'improved-infrastructure-tour',
    label: 'Improved Infrastructure Tour',
    description: 'Officials visit recently improved counties, claiming credit for visible development.',
    complexity: SIMPLE,
    family: 'infrastructure',
    scope: ['county'],
    level: 'county',
    party: 'yellow',
    selector: { minFeatures: { feature: 'improved_status_index', value: 0.55 } },
    magnitudeRange: [0.07, 0.18],
    tags: ['infrastructure', 'development', 'incumbency'],
    selectionWeight: 1.2,
    narrative: narrative('Newly improved districts become showcases for the establishment.', ['infrastructure tour', 'development showcase']),
    effects: [
      {
        id: 'improved-yellow-tour',
        level: 'county',
        party: 'yellow',
        selector: { minFeatures: { feature: 'improved_status_index', value: 0.55 } },
        weightBy: { feature: 'improved_status_index', minMultiplier: 0.9, maxMultiplier: 1.35 },
      },
    ],
  },
  {
    id: 'cultural-renaissance',
    label: 'Cultural Renaissance',
    description: 'A surge in cultural output gives reformers momentum in artistic and intellectual districts.',
    complexity: SIMPLE,
    family: 'culture',
    scope: ['county'],
    level: 'county',
    party: 'blue',
    selector: { minFeatures: { feature: 'cultural_output_index', value: 0.5 } },
    magnitudeRange: [0.08, 0.2],
    tags: ['culture', 'reform', 'intellectual'],
    selectionWeight: 1.1,
    narrative: narrative('Cultural vitality becomes a proxy for progressive politics.', ['cultural renaissance', 'artistic surge']),
    effects: [
      {
        id: 'cultural-blue-renaissance',
        level: 'county',
        party: 'blue',
        selector: { minFeatures: { feature: 'cultural_output_index', value: 0.5 } },
        weightBy: { feature: 'cultural_output_index', minMultiplier: 0.85, maxMultiplier: 1.4 },
      },
    ],
  },
  {
    id: 'roman-provincial-revival',
    label: 'Roman Provincial Revival',
    description: 'Strengthened Lotus networks mobilize Roman-identity provinces with unprecedented coordination.',
    complexity: SIMPLE,
    family: 'restoration',
    scope: ['province'],
    level: 'province',
    party: 'purple',
    selector: { minRomanIdentityIndex: 0.45 },
    magnitudeRange: [0.12, 0.28],
    tags: ['restoration', 'roman', 'minority', 'purple-boosted'],
    selectionWeight: 1.3,
    narrative: narrative('Roman identity provinces find new strength in coordinated restoration politics.', ['Roman revival', 'provincial coordination']),
    effects: [
      {
        id: 'roman-purple-revival',
        level: 'province',
        party: 'purple',
        selector: { minRomanIdentityIndex: 0.45 },
        weightBy: [
          { feature: 'roman_identity_index', minMultiplier: 1, maxMultiplier: 1.55 },
          { feature: 'restorationist_index', minMultiplier: 0.9, maxMultiplier: 1.4 },
        ],
      },
    ],
  },
]
