import { COMPOUND, STORYLINE, narrative } from './helpers'

export const STORY_TREND_TEMPLATES = [
  {
    id: 'capital-frontier-cleavage',
    label: 'Capital-Frontier Cleavage',
    description: 'The election splits into a capital core versus frontier autonomy story.',
    complexity: COMPOUND,
    family: 'autonomy',
    scope: ['region', 'province', 'county'],
    level: 'province',
    party: 'yellow',
    magnitudeRange: [0.18, 0.38],
    tags: ['centralization', 'autonomy', 'regional-cleavage'],
    selectionWeight: 1,
    narrative: narrative(
      'The imperial core asks for unity while distant provinces demand room to breathe.',
      ['center versus periphery', 'regional autonomy'],
      ['Core officials nationalize the stakes.', 'Petition committees emerge outside the capital.', 'Localist counties turn the argument into turnout.']
    ),
    interactions: [
      { withTags: ['security'], levels: ['national', 'province'], multiplier: 1.15 },
      { withTags: ['corruption'], levels: ['national', 'province'], multiplier: 0.85 },
    ],
    effects: [
      {
        id: 'core-yellow-boost',
        level: 'province',
        party: 'yellow',
        selector: { minImperialCoreIndex: 0.55 },
        magnitudeFactor: 0.95,
        weightBy: { feature: 'imperial_core_index', minMultiplier: 0.9, maxMultiplier: 1.35 },
      },
      {
        id: 'frontier-white-boost',
        level: 'province',
        party: 'white',
        selector: { any: [{ minLocalistIndex: 0.55 }, { isConquered: true }] },
        magnitudeFactor: 1.15,
        weightBy: { feature: 'localist_index', minMultiplier: 0.9, maxMultiplier: 1.45 },
        interactions: [{ withTags: ['autonomy'], levels: ['province', 'county'], multiplier: 1.12 }],
      },
      {
        id: 'localist-county-white-echo',
        level: 'county',
        party: 'white',
        selector: { minLocalistIndex: 0.55 },
        magnitudeFactor: 0.65,
        weightBy: { feature: 'localist_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
    ],
  },
  {
    id: 'general-strike-network',
    label: 'General Strike Network',
    description: 'A labor strike starts in industrial counties, attracts intellectual sympathy, and pressures the national vote.',
    complexity: STORYLINE,
    family: 'labor',
    scope: ['national', 'province', 'county'],
    level: 'county',
    party: 'orange',
    magnitudeRange: [0.20, 0.44],
    tags: ['labor', 'industrial', 'grievance', 'strike'],
    selectionWeight: 0.95,
    narrative: narrative(
      'A strike becomes a national argument over who built the empire and who benefited from it.',
      ['general strike', 'labor insurgency'],
      ['Factories organize first.', 'Campus districts debate solidarity.', 'National parties are forced to pick sides.']
    ),
    interactions: [
      { withTags: ['economy'], levels: ['national'], multiplier: 1.08 },
      { withTags: ['infrastructure'], levels: ['county'], multiplier: 1.12 },
    ],
    effects: [
      {
        id: 'industrial-orange-surge',
        level: 'county',
        party: 'orange',
        selector: { any: [{ minIndustrialIndex: 0.5 }, { minWorkerGrievanceIndex: 0.5 }] },
        weightBy: { feature: 'worker_grievance_index', fallbackKeys: ['worker_index'], minMultiplier: 0.9, maxMultiplier: 1.55 },
      },
      {
        id: 'campus-solidarity-blue',
        level: 'county',
        party: 'blue',
        selector: { minIntellectualIndex: 0.55 },
        magnitudeFactor: 0.45,
        weightBy: { feature: 'intellectual_index', minMultiplier: 0.85, maxMultiplier: 1.25 },
      },
      {
        id: 'national-labor-frame',
        level: 'national',
        party: 'orange',
        magnitudeFactor: 0.55,
      },
      {
        id: 'establishment-strike-drag',
        level: ['national', 'province'],
        party: 'yellow',
        mode: 'suppress',
        magnitudeFactor: 0.35,
        selector: {},
      },
    ],
  },
  {
    id: 'sacred-restoration-circuit',
    label: 'Sacred Restoration Circuit',
    description: 'Religious revival and restorationist memory reinforce one another in spiritual and Roman provinces.',
    complexity: STORYLINE,
    family: 'religion',
    scope: ['province', 'county'],
    level: 'province',
    party: 'purple',
    magnitudeRange: [0.18, 0.42],
    tags: ['religion', 'restoration', 'traditionalist'],
    selectionWeight: 0.9,
    narrative: narrative(
      'Shrines, old dynastic stories, and minority communities start speaking the same political language.',
      ['religious restoration', 'minority mobilization'],
      ['Spiritual counties revive old rites.', 'Roman provinces connect the revival to restoration.', 'Traditionalists and Lotus voters compete for the same sacred symbols.']
    ),
    interactions: [
      { withTags: ['restoration'], levels: ['province'], multiplier: 1.2 },
      { withTags: ['religion'], levels: ['province', 'county'], multiplier: 1.12 },
    ],
    effects: [
      {
        id: 'roman-purple-wave',
        level: 'province',
        party: 'purple',
        selector: { any: [{ minRomanIdentityIndex: 0.45 }, { minFeatures: { feature: 'restorationist_index', value: 0.55 } }] },
        weightBy: { feature: 'restorationist_index', minMultiplier: 0.9, maxMultiplier: 1.55 },
      },
      {
        id: 'spiritual-red-countercurrent',
        level: 'province',
        party: 'red',
        selector: { minSpiritualIndex: 0.55 },
        magnitudeFactor: 0.55,
        weightBy: { feature: 'traditionalist_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
      {
        id: 'holy-county-purple-echo',
        level: 'county',
        party: 'purple',
        selector: { minSpiritualIndex: 0.6 },
        magnitudeFactor: 0.6,
        weightBy: { feature: 'restorationist_index', minMultiplier: 0.8, maxMultiplier: 1.35 },
      },
    ],
  },
  {
    id: 'rail-and-factory-pact',
    label: 'Rail And Factory Pact',
    description: 'Infrastructure successes and factory wage bargaining create a cross-class development bargain.',
    complexity: COMPOUND,
    family: 'infrastructure',
    scope: ['province', 'county'],
    level: 'county',
    party: 'yellow',
    magnitudeRange: [0.16, 0.34],
    tags: ['infrastructure', 'labor', 'development'],
    selectionWeight: 1,
    narrative: narrative(
      'Rail builders and factory committees briefly agree that growth should be shared.',
      ['development bargain', 'infrastructure labor pact'],
      ['Rail counties reward the center.', 'Industrial workers demand a share.', 'Both parties benefit where tracks meet factories.']
    ),
    interactions: [
      { withTags: ['labor'], levels: ['county'], multiplier: 1.1 },
      { withTags: ['infrastructure'], levels: ['county'], multiplier: 1.1 },
    ],
    effects: [
      {
        id: 'infrastructure-yellow-boost',
        level: 'county',
        party: 'yellow',
        selector: { minInfrastructureIndex: 0.6 },
        weightBy: { feature: 'infrastructure_index', minMultiplier: 0.9, maxMultiplier: 1.45 },
      },
      {
        id: 'industrial-orange-bargain',
        level: 'county',
        party: 'orange',
        selector: { minIndustrialIndex: 0.5 },
        magnitudeFactor: 0.8,
        weightBy: { feature: 'industrial_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
      {
        id: 'developed-province-yellow-lift',
        level: 'province',
        party: 'yellow',
        selector: { minInfrastructureIndex: 0.55 },
        magnitudeFactor: 0.45,
        weightBy: { feature: 'infrastructure_index', minMultiplier: 0.85, maxMultiplier: 1.25 },
      },
    ],
  },
  {
    id: 'american-home-rule-campaign',
    label: 'American Home Rule Campaign',
    description: 'American provinces coordinate autonomy politics with localist counties and civic reformers.',
    complexity: STORYLINE,
    family: 'autonomy',
    scope: ['region', 'province', 'county'],
    level: 'province',
    party: 'white',
    selector: { groupIncludes: 'American' },
    magnitudeRange: [0.22, 0.5],
    tags: ['autonomy', 'american', 'regional-cleavage'],
    selectionWeight: 0.95,
    narrative: narrative(
      'Home rule becomes a disciplined regional campaign rather than a loose grievance.',
      ['American autonomy', 'home rule campaign'],
      ['Regional leaders coordinate messaging.', 'Localist counties become organizing bases.', 'Civic reformers offer institutional cover.']
    ),
    interactions: [
      { withTags: ['centralization'], levels: ['province', 'national'], multiplier: 1.18 },
      { withTags: ['corruption'], levels: ['national'], multiplier: 1.1 },
    ],
    effects: [
      {
        id: 'american-white-surge',
        level: 'province',
        party: 'white',
        selector: { groupIncludes: 'American' },
        weightBy: { feature: 'american_identity_index', minMultiplier: 1, maxMultiplier: 1.35 },
      },
      {
        id: 'localist-county-white-surge',
        level: 'county',
        party: 'white',
        selector: { minLocalistIndex: 0.5 },
        magnitudeFactor: 0.8,
        weightBy: { feature: 'localist_index', minMultiplier: 0.85, maxMultiplier: 1.4 },
      },
      {
        id: 'blue-institutional-allies',
        level: ['province', 'county'],
        party: 'blue',
        selector: { any: [{ minLocalistIndex: 0.45 }, { minIntellectualIndex: 0.55 }] },
        magnitudeFactor: 0.35,
      },
    ],
  },
  {
    id: 'border-war-rally',
    label: 'Border War Rally',
    description: 'A security crisis rallies loyalists and militarists while conquered provinces resist the frame.',
    complexity: COMPOUND,
    family: 'security',
    scope: ['national', 'province', 'county'],
    level: 'national',
    party: 'red',
    magnitudeRange: [0.18, 0.42],
    tags: ['security', 'military', 'centralization'],
    selectionWeight: 0.95,
    narrative: narrative(
      'A border scare turns security into the dominant lens, but not every province accepts the story.',
      ['war scare', 'security election'],
      ['National speeches harden the security vote.', 'Garrison counties move first.', 'Conquered provinces hear the message as occupation.']
    ),
    interactions: [
      { withTags: ['military'], levels: ['county'], multiplier: 1.15 },
      { withTags: ['autonomy'], levels: ['province'], multiplier: 0.92 },
    ],
    effects: [
      { id: 'national-red-rally', level: 'national', party: 'red', magnitudeFactor: 0.9 },
      {
        id: 'garrison-red-rally',
        level: 'county',
        party: 'red',
        selector: { minMilitaryIndex: 0.5 },
        magnitudeFactor: 1,
        weightBy: { feature: 'military_index', minMultiplier: 0.9, maxMultiplier: 1.5 },
      },
      {
        id: 'loyal-core-yellow-rally',
        level: 'province',
        party: 'yellow',
        selector: { minImperialCoreIndex: 0.55 },
        magnitudeFactor: 0.55,
        weightBy: { feature: 'imperial_core_index', minMultiplier: 0.9, maxMultiplier: 1.3 },
      },
      {
        id: 'conquered-white-backlash',
        level: 'province',
        party: 'white',
        selector: { isConquered: true },
        magnitudeFactor: 0.8,
      },
    ],
  },
  {
    id: 'capital-corruption-inquiry',
    label: 'Capital Corruption Inquiry',
    description: 'A corruption scandal in the imperial core hurts the establishment and activates reformers and workers.',
    complexity: COMPOUND,
    family: 'governance',
    scope: ['national', 'province', 'county'],
    level: 'province',
    party: 'blue',
    magnitudeRange: [0.16, 0.36],
    tags: ['corruption', 'reform', 'anti-establishment'],
    selectionWeight: 1,
    narrative: narrative(
      'The capital tries to contain a scandal that keeps leaking into local races.',
      ['corruption scandal', 'reform wave'],
      ['Imperial-core trust dips.', 'Civic reformers demand audits.', 'Worker districts connect corruption to wages.']
    ),
    effects: [
      {
        id: 'core-yellow-drag',
        level: ['national', 'province'],
        party: 'yellow',
        mode: 'suppress',
        selector: { any: [{ minImperialCoreIndex: 0.45 }, {}] },
        magnitudeFactor: 0.45,
      },
      {
        id: 'reform-blue-surge',
        level: ['national', 'province'],
        party: 'blue',
        selector: {},
        magnitudeFactor: 0.75,
      },
      {
        id: 'worker-orange-anger',
        level: 'county',
        party: 'orange',
        selector: { minWorkerGrievanceIndex: 0.45 },
        magnitudeFactor: 0.65,
        weightBy: { feature: 'worker_grievance_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
    ],
  },
  {
    id: 'food-price-crisis',
    label: 'Food Price Crisis',
    description: 'Urban hunger, rural resentment, and anti-incumbent anger collide.',
    complexity: STORYLINE,
    family: 'economy',
    scope: ['national', 'province', 'county'],
    level: 'county',
    party: 'orange',
    magnitudeRange: [0.18, 0.42],
    tags: ['economy', 'grievance', 'rural', 'labor'],
    selectionWeight: 0.95,
    narrative: narrative(
      'A food shock means different things in the city, the countryside, and the palace.',
      ['food crisis', 'cost of living'],
      ['Urban workers blame wages and prices.', 'Agrarian counties blame distant planners.', 'The establishment loses its aura of competence.']
    ),
    interactions: [
      { withTags: ['labor'], levels: ['county'], multiplier: 1.14 },
      { withTags: ['stability'], levels: ['national'], multiplier: 0.9 },
    ],
    effects: [
      {
        id: 'urban-orange-hunger',
        level: 'county',
        party: 'orange',
        selector: { minWorkerGrievanceIndex: 0.45 },
        weightBy: { feature: 'worker_grievance_index', minMultiplier: 0.9, maxMultiplier: 1.45 },
      },
      {
        id: 'agrarian-red-resentment',
        level: 'county',
        party: 'red',
        selector: { minAgrarianIndex: 0.55 },
        magnitudeFactor: 0.75,
        weightBy: { feature: 'agrarian_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
      {
        id: 'incumbent-food-drag',
        level: 'national',
        party: 'yellow',
        mode: 'suppress',
        magnitudeFactor: 0.55,
      },
    ],
  },
  {
    id: 'university-reform-network',
    label: 'University Reform Network',
    description: 'Campuses, theater districts, and professional neighborhoods coordinate a reformist narrative.',
    complexity: COMPOUND,
    family: 'modernization',
    scope: ['national', 'province', 'county'],
    level: 'county',
    party: 'blue',
    magnitudeRange: [0.15, 0.34],
    tags: ['education', 'reform', 'culture'],
    selectionWeight: 1,
    narrative: narrative(
      'Universities and cultural institutions turn elite conversation into campaign infrastructure.',
      ['university reform', 'cultural liberals'],
      ['Campus counties organize debates.', 'Cultural districts amplify the message.', 'The national reform vote gains coherence.']
    ),
    effects: [
      {
        id: 'intellectual-blue-surge',
        level: 'county',
        party: 'blue',
        selector: { minIntellectualIndex: 0.55 },
        weightBy: { feature: 'intellectual_index', minMultiplier: 0.9, maxMultiplier: 1.45 },
      },
      {
        id: 'cultural-blue-surge',
        level: 'county',
        party: 'blue',
        selector: { minCulturalEliteIndex: 0.55 },
        magnitudeFactor: 0.65,
        weightBy: { feature: 'cultural_elite_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
      {
        id: 'national-blue-coherence',
        level: 'national',
        party: 'blue',
        magnitudeFactor: 0.45,
      },
      {
        id: 'student-labor-link',
        level: 'county',
        party: 'orange',
        selector: { all: [{ minIntellectualIndex: 0.45 }, { minWorkerGrievanceIndex: 0.4 }] },
        magnitudeFactor: 0.35,
      },
    ],
  },
  {
    id: 'green-land-rights',
    label: 'Green Land Rights',
    description: 'Preserve, park, and rural counties turn conservation into a local-rights argument.',
    complexity: COMPOUND,
    family: 'localism',
    scope: ['province', 'county'],
    level: 'county',
    party: 'white',
    magnitudeRange: [0.14, 0.32],
    tags: ['localism', 'rural', 'reform'],
    selectionWeight: 0.95,
    narrative: narrative(
      'Land stewardship politics bridges rural autonomy and civic reform.',
      ['land rights', 'conservation politics'],
      ['Rural counties resist outside development.', 'High-appeal districts embrace stewardship language.', 'Reformers and localists share some voters.']
    ),
    effects: [
      {
        id: 'rural-white-land-boost',
        level: 'county',
        party: 'white',
        selector: { any: [{ minLocalistIndex: 0.55 }, { maxUrbanIndex: 0.35 }] },
        weightBy: { feature: 'localist_index', minMultiplier: 0.85, maxMultiplier: 1.45 },
      },
      {
        id: 'appeal-blue-stewardship',
        level: 'county',
        party: 'blue',
        selector: { minFeatures: { feature: 'appeal_index', value: 0.5 } },
        magnitudeFactor: 0.55,
        weightBy: { feature: 'appeal_index', minMultiplier: 0.85, maxMultiplier: 1.3 },
      },
    ],
  },
  {
    id: 'veterans-return',
    label: 'Veterans Return',
    description: 'Veterans come home with patriotic loyalties and economic demands.',
    complexity: COMPOUND,
    family: 'security',
    scope: ['province', 'county'],
    level: 'county',
    party: 'red',
    magnitudeRange: [0.14, 0.32],
    tags: ['military', 'labor', 'security'],
    selectionWeight: 0.9,
    narrative: narrative(
      'Veterans return as both patriotic validators and demanding constituents.',
      ['veteran politics', 'postwar economy'],
      ['Garrison communities reward traditionalists.', 'Industrial veterans press wage claims.', 'Loyal provinces respond most strongly.']
    ),
    effects: [
      {
        id: 'veteran-red-garrison',
        level: 'county',
        party: 'red',
        selector: { minMilitaryIndex: 0.45 },
        weightBy: { feature: 'military_index', minMultiplier: 0.9, maxMultiplier: 1.4 },
      },
      {
        id: 'veteran-orange-workshops',
        level: 'county',
        party: 'orange',
        selector: { all: [{ minMilitaryIndex: 0.25 }, { minIndustrialIndex: 0.45 }] },
        magnitudeFactor: 0.55,
      },
      {
        id: 'loyal-province-red-echo',
        level: 'province',
        party: 'red',
        selector: { minLoyaltyIndex: 0.7 },
        magnitudeFactor: 0.45,
      },
    ],
  },
]
