import { COMPOUND, STORYLINE, narrative } from './helpers'

export const STORY_TREND_TEMPLATES = [
  {
    id: 'capital-frontier-cleavage',
    label: 'Capital-Frontier Cleavage',
    description: 'The election splits into a capital core versus frontier autonomy story.',
    complexity: COMPOUND,
    family: 'autonomy',
    scope: ['region', 'province', 'county'],
    level: 'province',
    party: 'yellow',
    magnitudeRange: [0.18, 0.38],
    tags: ['centralization', 'autonomy', 'regional-cleavage'],
    selectionWeight: 1,
    narrative: narrative(
      'The imperial core asks for unity while distant provinces demand room to breathe.',
      ['center versus periphery', 'regional autonomy'],
      ['Core officials nationalize the stakes.', 'Petition committees emerge outside the capital.', 'Localist counties turn the argument into turnout.']
    ),
    interactions: [
      { withTags: ['security'], levels: ['national', 'province'], multiplier: 1.15 },
      { withTags: ['corruption'], levels: ['national', 'province'], multiplier: 0.85 },
    ],
    effects: [
      {
        id: 'core-yellow-boost',
        level: 'province',
        party: 'yellow',
        selector: { minImperialCoreIndex: 0.55 },
        magnitudeFactor: 0.95,
        weightBy: { feature: 'imperial_core_index', minMultiplier: 0.9, maxMultiplier: 1.35 },
      },
      {
        id: 'frontier-white-boost',
        level: 'province',
        party: 'white',
        selector: { any: [{ minLocalistIndex: 0.55 }, { isConquered: true }] },
        magnitudeFactor: 1.15,
        weightBy: { feature: 'localist_index', minMultiplier: 0.9, maxMultiplier: 1.45 },
        interactions: [{ withTags: ['autonomy'], levels: ['province', 'county'], multiplier: 1.12 }],
      },
      {
        id: 'localist-county-white-echo',
        level: 'county',
        party: 'white',
        selector: { minLocalistIndex: 0.55 },
        magnitudeFactor: 0.65,
        weightBy: { feature: 'localist_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
    ],
  },
  {
    id: 'general-strike-network',
    label: 'General Strike Network',
    description: 'A labor strike starts in industrial counties, attracts intellectual sympathy, and pressures the national vote.',
    complexity: STORYLINE,
    family: 'labor',
    scope: ['national', 'province', 'county'],
    level: 'county',
    party: 'orange',
    magnitudeRange: [0.20, 0.44],
    tags: ['labor', 'industrial', 'grievance', 'strike'],
    selectionWeight: 0.95,
    narrative: narrative(
      'A strike becomes a national argument over who built the empire and who benefited from it.',
      ['general strike', 'labor insurgency'],
      ['Factories organize first.', 'Campus districts debate solidarity.', 'National parties are forced to pick sides.']
    ),
    interactions: [
      { withTags: ['economy'], levels: ['national'], multiplier: 1.08 },
      { withTags: ['infrastructure'], levels: ['county'], multiplier: 1.12 },
    ],
    effects: [
      {
        id: 'industrial-orange-surge',
        level: 'county',
        party: 'orange',
        selector: { any: [{ minIndustrialIndex: 0.5 }, { minWorkerGrievanceIndex: 0.5 }] },
        weightBy: { feature: 'worker_grievance_index', fallbackKeys: ['worker_index'], minMultiplier: 0.9, maxMultiplier: 1.55 },
      },
      {
        id: 'campus-solidarity-blue',
        level: 'county',
        party: 'blue',
        selector: { minIntellectualIndex: 0.55 },
        magnitudeFactor: 0.45,
        weightBy: { feature: 'intellectual_index', minMultiplier: 0.85, maxMultiplier: 1.25 },
      },
      {
        id: 'national-labor-frame',
        level: 'national',
        party: 'orange',
        magnitudeFactor: 0.55,
      },
      {
        id: 'establishment-strike-drag',
        level: ['national', 'province'],
        party: 'yellow',
        mode: 'suppress',
        magnitudeFactor: 0.35,
        selector: {},
      },
    ],
  },
  {
    id: 'sacred-restoration-circuit',
    label: 'Sacred Restoration Circuit',
    description: 'Religious revival and restorationist memory reinforce one another in spiritual and Roman provinces.',
    complexity: STORYLINE,
    family: 'religion',
    scope: ['province', 'county'],
    level: 'province',
    party: 'purple',
    magnitudeRange: [0.18, 0.42],
    tags: ['religion', 'restoration', 'traditionalist'],
    selectionWeight: 0.9,
    narrative: narrative(
      'Shrines, old dynastic stories, and minority communities start speaking the same political language.',
      ['religious restoration', 'minority mobilization'],
      ['Spiritual counties revive old rites.', 'Roman provinces connect the revival to restoration.', 'Traditionalists and Lotus voters compete for the same sacred symbols.']
    ),
    interactions: [
      { withTags: ['restoration'], levels: ['province'], multiplier: 1.2 },
      { withTags: ['religion'], levels: ['province', 'county'], multiplier: 1.12 },
    ],
    effects: [
      {
        id: 'roman-purple-wave',
        level: 'province',
        party: 'purple',
        selector: { any: [{ minRomanIdentityIndex: 0.45 }, { minFeatures: { feature: 'restorationist_index', value: 0.55 } }] },
        weightBy: { feature: 'restorationist_index', minMultiplier: 0.9, maxMultiplier: 1.55 },
      },
      {
        id: 'spiritual-red-countercurrent',
        level: 'province',
        party: 'red',
        selector: { minSpiritualIndex: 0.55 },
        magnitudeFactor: 0.55,
        weightBy: { feature: 'traditionalist_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
      {
        id: 'holy-county-purple-echo',
        level: 'county',
        party: 'purple',
        selector: { minSpiritualIndex: 0.6 },
        magnitudeFactor: 0.6,
        weightBy: { feature: 'restorationist_index', minMultiplier: 0.8, maxMultiplier: 1.35 },
      },
    ],
  },
  {
    id: 'rail-and-factory-pact',
    label: 'Rail And Factory Pact',
    description: 'Infrastructure successes and factory wage bargaining create a cross-class development bargain.',
    complexity: COMPOUND,
    family: 'infrastructure',
    scope: ['province', 'county'],
    level: 'county',
    party: 'yellow',
    magnitudeRange: [0.16, 0.34],
    tags: ['infrastructure', 'labor', 'development'],
    selectionWeight: 1,
    narrative: narrative(
      'Rail builders and factory committees briefly agree that growth should be shared.',
      ['development bargain', 'infrastructure labor pact'],
      ['Rail counties reward the center.', 'Industrial workers demand a share.', 'Both parties benefit where tracks meet factories.']
    ),
    interactions: [
      { withTags: ['labor'], levels: ['county'], multiplier: 1.1 },
      { withTags: ['infrastructure'], levels: ['county'], multiplier: 1.1 },
    ],
    effects: [
      {
        id: 'infrastructure-yellow-boost',
        level: 'county',
        party: 'yellow',
        selector: { minInfrastructureIndex: 0.6 },
        weightBy: { feature: 'infrastructure_index', minMultiplier: 0.9, maxMultiplier: 1.45 },
      },
      {
        id: 'industrial-orange-bargain',
        level: 'county',
        party: 'orange',
        selector: { minIndustrialIndex: 0.5 },
        magnitudeFactor: 0.8,
        weightBy: { feature: 'industrial_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
      {
        id: 'developed-province-yellow-lift',
        level: 'province',
        party: 'yellow',
        selector: { minInfrastructureIndex: 0.55 },
        magnitudeFactor: 0.45,
        weightBy: { feature: 'infrastructure_index', minMultiplier: 0.85, maxMultiplier: 1.25 },
      },
    ],
  },
  {
    id: 'american-home-rule-campaign',
    label: 'American Home Rule Campaign',
    description: 'American provinces coordinate autonomy politics with localist counties and civic reformers.',
    complexity: STORYLINE,
    family: 'autonomy',
    scope: ['region', 'province', 'county'],
    level: 'province',
    party: 'white',
    selector: { groupIncludes: 'American' },
    magnitudeRange: [0.22, 0.5],
    tags: ['autonomy', 'american', 'regional-cleavage'],
    selectionWeight: 0.95,
    narrative: narrative(
      'Home rule becomes a disciplined regional campaign rather than a loose grievance.',
      ['American autonomy', 'home rule campaign'],
      ['Regional leaders coordinate messaging.', 'Localist counties become organizing bases.', 'Civic reformers offer institutional cover.']
    ),
    interactions: [
      { withTags: ['centralization'], levels: ['province', 'national'], multiplier: 1.18 },
      { withTags: ['corruption'], levels: ['national'], multiplier: 1.1 },
    ],
    effects: [
      {
        id: 'american-white-surge',
        level: 'province',
        party: 'white',
        selector: { groupIncludes: 'American' },
        weightBy: { feature: 'american_identity_index', minMultiplier: 1, maxMultiplier: 1.35 },
      },
      {
        id: 'localist-county-white-surge',
        level: 'county',
        party: 'white',
        selector: { minLocalistIndex: 0.5 },
        magnitudeFactor: 0.8,
        weightBy: { feature: 'localist_index', minMultiplier: 0.85, maxMultiplier: 1.4 },
      },
      {
        id: 'blue-institutional-allies',
        level: ['province', 'county'],
        party: 'blue',
        selector: { any: [{ minLocalistIndex: 0.45 }, { minIntellectualIndex: 0.55 }] },
        magnitudeFactor: 0.35,
      },
    ],
  },
  {
    id: 'border-war-rally',
    label: 'Border War Rally',
    description: 'A security crisis rallies loyalists and militarists while conquered provinces resist the frame.',
    complexity: COMPOUND,
    family: 'security',
    scope: ['national', 'province', 'county'],
    level: 'national',
    party: 'red',
    magnitudeRange: [0.18, 0.42],
    tags: ['security', 'military', 'centralization'],
    selectionWeight: 0.95,
    narrative: narrative(
      'A border scare turns security into the dominant lens, but not every province accepts the story.',
      ['war scare', 'security election'],
      ['National speeches harden the security vote.', 'Garrison counties move first.', 'Conquered provinces hear the message as occupation.']
    ),
    interactions: [
      { withTags: ['military'], levels: ['county'], multiplier: 1.15 },
      { withTags: ['autonomy'], levels: ['province'], multiplier: 0.92 },
    ],
    effects: [
      { id: 'national-red-rally', level: 'national', party: 'red', magnitudeFactor: 0.9 },
      {
        id: 'garrison-red-rally',
        level: 'county',
        party: 'red',
        selector: { minMilitaryIndex: 0.5 },
        magnitudeFactor: 1,
        weightBy: { feature: 'military_index', minMultiplier: 0.9, maxMultiplier: 1.5 },
      },
      {
        id: 'loyal-core-yellow-rally',
        level: 'province',
        party: 'yellow',
        selector: { minImperialCoreIndex: 0.55 },
        magnitudeFactor: 0.55,
        weightBy: { feature: 'imperial_core_index', minMultiplier: 0.9, maxMultiplier: 1.3 },
      },
      {
        id: 'conquered-white-backlash',
        level: 'province',
        party: 'white',
        selector: { isConquered: true },
        magnitudeFactor: 0.8,
      },
    ],
  },
  {
    id: 'capital-corruption-inquiry',
    label: 'Capital Corruption Inquiry',
    description: 'A corruption scandal in the imperial core hurts the establishment and activates reformers and workers.',
    complexity: COMPOUND,
    family: 'governance',
    scope: ['national', 'province', 'county'],
    level: 'province',
    party: 'blue',
    magnitudeRange: [0.16, 0.36],
    tags: ['corruption', 'reform', 'anti-establishment'],
    selectionWeight: 1,
    narrative: narrative(
      'The capital tries to contain a scandal that keeps leaking into local races.',
      ['corruption scandal', 'reform wave'],
      ['Imperial-core trust dips.', 'Civic reformers demand audits.', 'Worker districts connect corruption to wages.']
    ),
    effects: [
      {
        id: 'core-yellow-drag',
        level: ['national', 'province'],
        party: 'yellow',
        mode: 'suppress',
        selector: { any: [{ minImperialCoreIndex: 0.45 }, {}] },
        magnitudeFactor: 0.45,
      },
      {
        id: 'reform-blue-surge',
        level: ['national', 'province'],
        party: 'blue',
        selector: {},
        magnitudeFactor: 0.75,
      },
      {
        id: 'worker-orange-anger',
        level: 'county',
        party: 'orange',
        selector: { minWorkerGrievanceIndex: 0.45 },
        magnitudeFactor: 0.65,
        weightBy: { feature: 'worker_grievance_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
    ],
  },
  {
    id: 'food-price-crisis',
    label: 'Food Price Crisis',
    description: 'Urban hunger, rural resentment, and anti-incumbent anger collide.',
    complexity: STORYLINE,
    family: 'economy',
    scope: ['national', 'province', 'county'],
    level: 'county',
    party: 'orange',
    magnitudeRange: [0.18, 0.42],
    tags: ['economy', 'grievance', 'rural', 'labor'],
    selectionWeight: 0.95,
    narrative: narrative(
      'A food shock means different things in the city, the countryside, and the palace.',
      ['food crisis', 'cost of living'],
      ['Urban workers blame wages and prices.', 'Agrarian counties blame distant planners.', 'The establishment loses its aura of competence.']
    ),
    interactions: [
      { withTags: ['labor'], levels: ['county'], multiplier: 1.14 },
      { withTags: ['stability'], levels: ['national'], multiplier: 0.9 },
    ],
    effects: [
      {
        id: 'urban-orange-hunger',
        level: 'county',
        party: 'orange',
        selector: { minWorkerGrievanceIndex: 0.45 },
        weightBy: { feature: 'worker_grievance_index', minMultiplier: 0.9, maxMultiplier: 1.45 },
      },
      {
        id: 'agrarian-red-resentment',
        level: 'county',
        party: 'red',
        selector: { minAgrarianIndex: 0.55 },
        magnitudeFactor: 0.75,
        weightBy: { feature: 'agrarian_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
      {
        id: 'incumbent-food-drag',
        level: 'national',
        party: 'yellow',
        mode: 'suppress',
        magnitudeFactor: 0.55,
      },
    ],
  },
  {
    id: 'university-reform-network',
    label: 'University Reform Network',
    description: 'Campuses, theater districts, and professional neighborhoods coordinate a reformist narrative.',
    complexity: COMPOUND,
    family: 'modernization',
    scope: ['national', 'province', 'county'],
    level: 'county',
    party: 'blue',
    magnitudeRange: [0.15, 0.34],
    tags: ['education', 'reform', 'culture'],
    selectionWeight: 1,
    narrative: narrative(
      'Universities and cultural institutions turn elite conversation into campaign infrastructure.',
      ['university reform', 'cultural liberals'],
      ['Campus counties organize debates.', 'Cultural districts amplify the message.', 'The national reform vote gains coherence.']
    ),
    effects: [
      {
        id: 'intellectual-blue-surge',
        level: 'county',
        party: 'blue',
        selector: { minIntellectualIndex: 0.55 },
        weightBy: { feature: 'intellectual_index', minMultiplier: 0.9, maxMultiplier: 1.45 },
      },
      {
        id: 'cultural-blue-surge',
        level: 'county',
        party: 'blue',
        selector: { minCulturalEliteIndex: 0.55 },
        magnitudeFactor: 0.65,
        weightBy: { feature: 'cultural_elite_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
      {
        id: 'national-blue-coherence',
        level: 'national',
        party: 'blue',
        magnitudeFactor: 0.45,
      },
      {
        id: 'student-labor-link',
        level: 'county',
        party: 'orange',
        selector: { all: [{ minIntellectualIndex: 0.45 }, { minWorkerGrievanceIndex: 0.4 }] },
        magnitudeFactor: 0.35,
      },
    ],
  },
  {
    id: 'green-land-rights',
    label: 'Green Land Rights',
    description: 'Preserve, park, and rural counties turn conservation into a local-rights argument.',
    complexity: COMPOUND,
    family: 'localism',
    scope: ['province', 'county'],
    level: 'county',
    party: 'white',
    magnitudeRange: [0.14, 0.32],
    tags: ['localism', 'rural', 'reform'],
    selectionWeight: 0.95,
    narrative: narrative(
      'Land stewardship politics bridges rural autonomy and civic reform.',
      ['land rights', 'conservation politics'],
      ['Rural counties resist outside development.', 'High-appeal districts embrace stewardship language.', 'Reformers and localists share some voters.']
    ),
    effects: [
      {
        id: 'rural-white-land-boost',
        level: 'county',
        party: 'white',
        selector: { any: [{ minLocalistIndex: 0.55 }, { maxUrbanIndex: 0.35 }] },
        weightBy: { feature: 'localist_index', minMultiplier: 0.85, maxMultiplier: 1.45 },
      },
      {
        id: 'appeal-blue-stewardship',
        level: 'county',
        party: 'blue',
        selector: { minFeatures: { feature: 'appeal_index', value: 0.5 } },
        magnitudeFactor: 0.55,
        weightBy: { feature: 'appeal_index', minMultiplier: 0.85, maxMultiplier: 1.3 },
      },
    ],
  },
  {
    id: 'veterans-return',
    label: 'Veterans Return',
    description: 'Veterans come home with patriotic loyalties and economic demands.',
    complexity: COMPOUND,
    family: 'security',
    scope: ['province', 'county'],
    level: 'county',
    party: 'red',
    magnitudeRange: [0.14, 0.32],
    tags: ['military', 'labor', 'security'],
    selectionWeight: 0.9,
    narrative: narrative(
      'Veterans return as both patriotic validators and demanding constituents.',
      ['veteran politics', 'postwar economy'],
      ['Garrison communities reward traditionalists.', 'Industrial veterans press wage claims.', 'Loyal provinces respond most strongly.']
    ),
    effects: [
      {
        id: 'veteran-red-garrison',
        level: 'county',
        party: 'red',
        selector: { minMilitaryIndex: 0.45 },
        weightBy: { feature: 'military_index', minMultiplier: 0.9, maxMultiplier: 1.4 },
      },
      {
        id: 'veteran-orange-workshops',
        level: 'county',
        party: 'orange',
        selector: { all: [{ minMilitaryIndex: 0.25 }, { minIndustrialIndex: 0.45 }] },
        magnitudeFactor: 0.55,
      },
      {
        id: 'loyal-province-red-echo',
        level: 'province',
        party: 'red',
        selector: { minLoyaltyIndex: 0.7 },
        magnitudeFactor: 0.45,
      },
    ],
  },
  {
    id: 'temple-and-granary-truce',
    label: 'Temple And Granary Truce',
    description: 'Food relief, shrine networks, and rural elders cool the campaign without erasing partisan stakes.',
    complexity: COMPOUND,
    family: 'stability',
    scope: ['national', 'province', 'county'],
    level: 'province',
    party: 'yellow',
    magnitudeRange: [0.12, 0.28],
    tags: ['stability', 'religion', 'rural', 'calming'],
    selectionWeight: 1.05,
    narrative: narrative(
      'Granary managers and temple elders make the election feel less desperate.',
      ['rural calm', 'temple granary politics'],
      ['Food stores blunt grievance.', 'Shrine committees validate continuity.', 'Agrarian counties reward order more than drama.']
    ),
    interactions: [
      { withTags: ['economy'], levels: ['national', 'county'], multiplier: 0.92 },
      { withTags: ['religion'], levels: ['province', 'county'], multiplier: 1.1 },
    ],
    effects: [
      {
        id: 'food-yellow-truce',
        level: 'province',
        party: 'yellow',
        selector: { minFeatures: { feature: 'food_index', value: 0.5 } },
        magnitudeFactor: 0.8,
        weightBy: { feature: 'food_index', minMultiplier: 0.85, maxMultiplier: 1.3 },
      },
      {
        id: 'spiritual-red-truce',
        level: 'county',
        party: 'red',
        selector: { minSpiritualIndex: 0.5 },
        magnitudeFactor: 0.75,
        weightBy: { feature: 'spiritual_index', minMultiplier: 0.85, maxMultiplier: 1.3 },
      },
      {
        id: 'grievance-orange-truce-drag',
        level: ['national', 'county'],
        party: 'orange',
        mode: 'suppress',
        selector: {},
        magnitudeFactor: 0.28,
      },
    ],
  },
  {
    id: 'provincial-reconciliation-tour',
    label: 'Provincial Reconciliation Tour',
    description: 'Imperial ministers and local leaders make a careful tour through low-loyalty provinces.',
    complexity: COMPOUND,
    family: 'autonomy',
    scope: ['province', 'county'],
    level: 'province',
    party: 'white',
    magnitudeRange: [0.12, 0.3],
    tags: ['autonomy', 'governance', 'localism', 'calming'],
    selectionWeight: 1,
    narrative: narrative(
      'A reconciliation tour turns autonomy arguments toward negotiated power instead of rupture.',
      ['reconciliation tour', 'local accommodation'],
      ['Localist provinces are treated as partners.', 'Core loyalists get reassurance.', 'Reformers sell process over confrontation.']
    ),
    interactions: [
      { withTags: ['centralization'], levels: ['province'], multiplier: 0.9 },
      { withTags: ['reform'], levels: ['province', 'county'], multiplier: 1.08 },
    ],
    effects: [
      {
        id: 'localist-white-reconciliation',
        level: 'province',
        party: 'white',
        selector: { any: [{ minLocalistIndex: 0.5 }, { maxLoyaltyIndex: 0.45 }] },
        weightBy: { feature: 'localist_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
      {
        id: 'process-blue-reconciliation',
        level: ['province', 'county'],
        party: 'blue',
        selector: { any: [{ minIntellectualIndex: 0.45 }, { minLocalistIndex: 0.45 }] },
        magnitudeFactor: 0.55,
      },
      {
        id: 'loyal-yellow-reassurance',
        level: 'province',
        party: 'yellow',
        selector: { minLoyaltyIndex: 0.65 },
        magnitudeFactor: 0.45,
      },
    ],
  },
  {
    id: 'workshop-arbitration-season',
    label: 'Workshop Arbitration Season',
    description: 'Factory committees and magistrates settle enough wage disputes to make labor politics practical rather than explosive.',
    complexity: COMPOUND,
    family: 'labor',
    scope: ['province', 'county'],
    level: 'county',
    party: 'orange',
    magnitudeRange: [0.12, 0.28],
    tags: ['labor', 'industrial', 'governance', 'calming'],
    selectionWeight: 1,
    narrative: narrative(
      'Labor remains organized, but arbitration turns anger into negotiated gains.',
      ['wage arbitration', 'settled workshops'],
      ['Industrial counties still lean labor.', 'Reform lawyers gain credibility.', 'Strike rhetoric loses some heat.']
    ),
    interactions: [
      { withTags: ['strike'], levels: ['county', 'national'], multiplier: 0.88 },
      { withTags: ['governance'], levels: ['province', 'county'], multiplier: 1.08 },
    ],
    effects: [
      {
        id: 'arbitrated-orange-workers',
        level: 'county',
        party: 'orange',
        selector: { minIndustrialIndex: 0.45 },
        weightBy: { feature: 'worker_index', minMultiplier: 0.85, maxMultiplier: 1.3 },
      },
      {
        id: 'arbitration-blue-lawyers',
        level: 'county',
        party: 'blue',
        selector: { any: [{ minIntellectualIndex: 0.45 }, { minCommercialMiddleClassIndex: 0.5 }] },
        magnitudeFactor: 0.55,
      },
      {
        id: 'strike-edge-muted',
        level: ['national', 'county'],
        party: 'orange',
        mode: 'suppress',
        selector: { minWorkerGrievanceIndex: 0.65 },
        magnitudeFactor: 0.25,
      },
    ],
  },
  {
    id: 'market-treaty-season',
    label: 'Market Treaty Season',
    description: 'Merchants, transport offices, and reform councils settle into a low-drama commercial upswing.',
    complexity: COMPOUND,
    family: 'commerce',
    scope: ['national', 'province', 'county'],
    level: 'county',
    party: 'blue',
    magnitudeRange: [0.12, 0.3],
    tags: ['commerce', 'infrastructure', 'reform', 'calming'],
    selectionWeight: 1.05,
    narrative: narrative(
      'Trade politics rewards competence, bridges, ledgers, and predictable rules.',
      ['commercial calm', 'market treaty'],
      ['Commercial counties listen to reformers.', 'Infrastructure counties credit the center.', 'The national tone becomes managerial.']
    ),
    interactions: [
      { withTags: ['infrastructure'], levels: ['county'], multiplier: 1.1 },
      { withTags: ['corruption'], levels: ['national'], multiplier: 0.9 },
    ],
    effects: [
      {
        id: 'commercial-blue-treaty',
        level: 'county',
        party: 'blue',
        selector: { minCommercialMiddleClassIndex: 0.5 },
        weightBy: { feature: 'commercial_middle_class_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
      {
        id: 'infrastructure-yellow-treaty',
        level: 'county',
        party: 'yellow',
        selector: { minInfrastructureIndex: 0.55 },
        magnitudeFactor: 0.75,
        weightBy: { feature: 'infrastructure_index', minMultiplier: 0.85, maxMultiplier: 1.3 },
      },
      {
        id: 'national-blue-managerial',
        level: 'national',
        party: 'blue',
        magnitudeFactor: 0.35,
      },
    ],
  },
  {
    id: 'citizenship-festival-circuit',
    label: 'Citizenship Festival Circuit',
    description: 'Public festivals, school ceremonies, and local associations make belonging feel ceremonial and civic.',
    complexity: STORYLINE,
    family: 'identity',
    scope: ['national', 'province', 'county'],
    level: 'province',
    party: 'yellow',
    magnitudeRange: [0.13, 0.32],
    tags: ['identity', 'culture', 'centralization', 'calming'],
    selectionWeight: 0.95,
    narrative: narrative(
      'The state sells unity through civic ritual rather than fear.',
      ['citizenship festivals', 'civic unity'],
      ['Core provinces embrace the ceremonies.', 'Schools and theaters carry the message.', 'Some localists accept inclusion while guarding autonomy.']
    ),
    interactions: [
      { withTags: ['security'], levels: ['national'], multiplier: 0.94 },
      { withTags: ['culture'], levels: ['county'], multiplier: 1.1 },
    ],
    effects: [
      {
        id: 'core-yellow-citizenship',
        level: 'province',
        party: 'yellow',
        selector: { minImperialCoreIndex: 0.5 },
        weightBy: { feature: 'imperial_core_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
      {
        id: 'cultural-blue-citizenship',
        level: 'county',
        party: 'blue',
        selector: { any: [{ minCulturalEliteIndex: 0.5 }, { minIntellectualIndex: 0.45 }] },
        magnitudeFactor: 0.65,
        weightBy: { feature: 'cultural_elite_index', fallbackKeys: ['intellectual_index'], minMultiplier: 0.85, maxMultiplier: 1.3 },
      },
      {
        id: 'localist-white-citizenship-echo',
        level: 'province',
        party: 'white',
        selector: { minLocalistIndex: 0.5 },
        magnitudeFactor: 0.35,
      },
    ],
  },
  {
    id: 'roads-before-rhetoric',
    label: 'Roads Before Rhetoric',
    description: 'Routine infrastructure delivery crowds out ideological speeches in connected and growing provinces.',
    complexity: COMPOUND,
    family: 'infrastructure',
    scope: ['province', 'county'],
    level: 'county',
    party: 'yellow',
    magnitudeRange: [0.12, 0.3],
    tags: ['infrastructure', 'development', 'stability', 'calming'],
    selectionWeight: 1.05,
    narrative: narrative(
      'The campaign becomes a list of roads, depots, and river crossings.',
      ['infrastructure delivery', 'practical development'],
      ['Connected counties reward delivery.', 'Commercial districts like the predictability.', 'Sharper ideological appeals lose a little space.']
    ),
    interactions: [
      { withTags: ['development'], levels: ['county', 'province'], multiplier: 1.1 },
      { withTags: ['anti-establishment'], levels: ['national'], multiplier: 0.92 },
    ],
    effects: [
      {
        id: 'connected-yellow-roads',
        level: 'county',
        party: 'yellow',
        selector: { minInfrastructureIndex: 0.5 },
        weightBy: { feature: 'infrastructure_index', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
      {
        id: 'commercial-blue-roads',
        level: 'county',
        party: 'blue',
        selector: { minCommercialMiddleClassIndex: 0.5 },
        magnitudeFactor: 0.55,
        weightBy: { feature: 'commercial_middle_class_index', minMultiplier: 0.85, maxMultiplier: 1.25 },
      },
      {
        id: 'anti-establishment-road-drag',
        level: 'national',
        party: 'orange',
        mode: 'suppress',
        selector: {},
        magnitudeFactor: 0.22,
      },
    ],
  },
  {
    id: 'minority-rights-roundtable',
    label: 'Minority Rights Roundtable',
    description: 'Minority communities, reformers, and localists find a shared but measured rights agenda.',
    complexity: COMPOUND,
    family: 'minority',
    scope: ['province', 'county'],
    level: 'province',
    party: 'purple',
    magnitudeRange: [0.13, 0.32],
    tags: ['minority', 'reform', 'localism', 'calming'],
    selectionWeight: 0.95,
    narrative: narrative(
      'Rights politics becomes procedural, local, and coalition-minded rather than apocalyptic.',
      ['minority rights', 'rights roundtable'],
      ['Minority provinces consolidate around Lotus organizers.', 'Reformers provide institutional language.', 'Localists see space for autonomy.']
    ),
    interactions: [
      { withTags: ['restoration'], levels: ['province'], multiplier: 0.92 },
      { withTags: ['reform'], levels: ['province', 'county'], multiplier: 1.1 },
    ],
    effects: [
      {
        id: 'minority-purple-roundtable',
        level: 'province',
        party: 'purple',
        selector: { minFeatures: { feature: 'minority_religion_share', value: 0.35 } },
        weightBy: { feature: 'minority_religion_share', minMultiplier: 0.85, maxMultiplier: 1.35 },
      },
      {
        id: 'blue-rights-law',
        level: ['province', 'county'],
        party: 'blue',
        selector: { any: [{ minIntellectualIndex: 0.45 }, { minCommercialMiddleClassIndex: 0.45 }] },
        magnitudeFactor: 0.55,
      },
      {
        id: 'white-local-rights-echo',
        level: 'province',
        party: 'white',
        selector: { minLocalistIndex: 0.45 },
        magnitudeFactor: 0.45,
      },
    ],
  },
  {
    id: 'elders-council-election',
    label: 'Elders Council Election',
    description: 'Local elders, rural notables, and shrine committees make the campaign slower and more traditional.',
    complexity: COMPOUND,
    family: 'religion',
    scope: ['province', 'county'],
    level: 'county',
    party: 'red',
    magnitudeRange: [0.12, 0.28],
    tags: ['religion', 'rural', 'traditionalist', 'calming'],
    selectionWeight: 1,
    narrative: narrative(
      'The loudest rallies give way to courtyard meetings and elder endorsements.',
      ['elders council', 'traditional quiet campaign'],
      ['Rural counties respond to notables.', 'Spiritual districts hear continuity language.', 'Urban reformers retain a small countercurrent.']
    ),
    interactions: [
      { withTags: ['rural'], levels: ['county'], multiplier: 1.1 },
      { withTags: ['modernization'], levels: ['county'], multiplier: 0.94 },
    ],
    effects: [
      {
        id: 'rural-red-elders',
        level: 'county',
        party: 'red',
        selector: { any: [{ minAgrarianIndex: 0.45 }, { minSpiritualIndex: 0.5 }] },
        weightBy: [
          { feature: 'agrarian_index', minMultiplier: 0.85, maxMultiplier: 1.25 },
          { feature: 'spiritual_index', minMultiplier: 0.85, maxMultiplier: 1.25 },
        ],
      },
      {
        id: 'localist-white-elders',
        level: 'province',
        party: 'white',
        selector: { minLocalistIndex: 0.45 },
        magnitudeFactor: 0.4,
      },
      {
        id: 'urban-blue-elder-countercurrent',
        level: 'county',
        party: 'blue',
        selector: { minFeatures: { feature: 'urban_index', value: 0.55 } },
        magnitudeFactor: 0.3,
      },
    ],
  },
]
