/**
 * DEFAULT party configuration — the data form of the original hand-tuned Khmer
 * engine. Each party carries, per scope (county / province / national):
 *   - bias[scope]:   the constant base term (folds in the old PARTY_FLOORS base)
 *   - affinities[scope][featureKey]: linear weight on that feature
 *
 * score(party, unit) = bias[scope] + Σ affinities[scope][feat] * featureValue[feat]
 *                      + Σ voter-bloc contributions (see defaultVoterBlocs.js)
 *
 * The five non-identity parties (yellow/orange/red/blue/green) are an exact
 * transcription of the original scoring/*.js coefficients. white & purple carry
 * their "diaspora" (default) base here; their "natural" identity boosts live in
 * the voter-bloc layer.
 *
 * Feature keys are the SAME ones emitted by features/*.js, plus three derived at
 * scoring time: cross_continental_index, conquered_index (province + county),
 * inverse_science_culture_index (county).
 */

export const DEFAULT_PARTIES = [
  {
    id: 'yellow',
    name: 'Divinus Sol',
    abbreviation: 'DS',
    colorName: 'Yellow',
    color: '#d4a843',
    ideology: 'Imperial centralist, enlightened elite, state-development party',
    coalitionPartners: ['orange', 'red', 'blue', 'purple', 'white'],
    bias: { county: 0.045, province: 0.056, national: 0.056 },
    affinities: {
      county: {
        imperial_core_index: 0.165,
        cultural_elite_index: 0.145,
        intellectual_index: 0.12,
        infrastructure_index: 0.09,
        improved_status_index: 0.08,
        state_religion_share: 0.07,
        religious_homogeneity_index: 0.05,
        civic_monument_index: 0.05,
        residential_index: 0.04,
        loyalty_index: 0.048,
        conquered_index: -0.19,
        localist_index: -0.09,
      },
      province: {
        imperial_core_index: 0.235,
        cultural_elite_index: 0.165,
        state_religion_share: 0.125,
        science_index: 0.10,
        culture_index: 0.10,
        development_index: 0.08,
        provincial_power_index: 0.07,
        loyalty_index: 0.08,
        religious_homogeneity_index: 0.05,
        civic_monument_index: 0.05,
        residential_index: 0.03,
        connectedness_index: 0.04,
        same_continent_index: 0.04,
        conquered_index: -0.215,
        localist_index: -0.11,
        foreign_origin_index: -0.09,
        frontier_index: -0.05,
      },
      national: {
        imperial_core_index: 0.18,
        culture_index: 0.16,
        science_index: 0.125,
        state_religion_share: 0.09,
        development_index: 0.08,
        provincial_power_index: 0.07,
        religious_homogeneity_index: 0.05,
        civic_monument_index: 0.04,
        residential_index: 0.03,
        loyalty_index: 0.075,
      },
    },
  },
  {
    id: 'orange',
    name: 'United Workers Congress',
    abbreviation: 'UWC',
    colorName: 'Orange',
    color: '#fb923c',
    ideology: 'Labor, industrial workers, organized production, urban economic justice',
    coalitionPartners: ['blue', 'yellow', 'red', 'white', 'purple'],
    bias: { county: 0.12, province: 0.12, national: 0.12 },
    affinities: {
      county: {
        industrial_index: 0.37,
        worker_index: 0.3,
        urban_index: 0.19,
        production_index: 0.16,
        yield_diversity_index: 0.13,
        mine_or_corporation_index: 0.1,
        extractive_index: 0.09,
        maritime_index: 0.07,
        worker_grievance_index: 0.1,
        spiritual_index: -0.08,
        imperial_core_index: -0.06,
      },
      province: {
        industrial_index: 0.36,
        production_index: 0.26,
        urbanization_index: 0.21,
        worker_grievance_index: 0.18,
        economic_diversity_index: 0.14,
        extractive_index: 0.1,
        maritime_index: 0.07,
        commerce_index: 0.11,
        faith_index: -0.06,
      },
      national: {
        industrial_index: 0.32,
        production_index: 0.24,
        urbanization_index: 0.19,
        worker_grievance_index: 0.16,
        economic_diversity_index: 0.13,
        extractive_index: 0.09,
        maritime_index: 0.07,
        improved_status_index: 0.06,
      },
    },
  },
  {
    id: 'red',
    name: 'The National Drumbeat',
    abbreviation: 'ND',
    colorName: 'Red',
    color: '#ef4444',
    ideology: 'Rural, military, socially conservative, patriotic traditionalist',
    coalitionPartners: ['purple', 'yellow', 'orange', 'white', 'blue'],
    bias: { county: 0.08, province: 0.1, national: 0.1 },
    affinities: {
      county: {
        agrarian_index: 0.32,
        rural_index: 0.22,
        military_index: 0.2,
        food_index: 0.14,
        traditionalist_index: 0.12,
        isolation_index: 0.1,
        wilderness_index: 0.08,
        mountain_index: 0.05,
        extractive_index: 0.04,
        inverse_science_culture_index: 0.06,
        urban_index: -0.1,
      },
      province: {
        agrarian_index: 0.3,
        military_index: 0.22,
        rural_index: 0.18,
        food_index: 0.14,
        traditionalist_index: 0.12,
        isolation_index: 0.1,
        wilderness_index: 0.08,
        mountain_index: 0.04,
        cross_continental_index: 0.02,
        urbanization_index: -0.08,
      },
      national: {
        agrarian_index: 0.32,
        military_index: 0.22,
        rural_index: 0.18,
        food_index: 0.14,
        traditionalist_index: 0.12,
        isolation_index: 0.1,
        wilderness_index: 0.08,
        mountain_index: 0.04,
      },
    },
  },
  {
    id: 'blue',
    name: 'Coalition of the Free',
    abbreviation: 'CF',
    colorName: 'Blue',
    color: '#60a5fa',
    ideology: 'Civic middle class, intellectuals, spiritual reformers, decentralists',
    coalitionPartners: ['orange', 'purple', 'yellow', 'white', 'red'],
    bias: { county: 0.11, province: 0.11, national: 0.11 },
    affinities: {
      county: {
        intellectual_index: 0.22,
        spiritual_index: 0.2,
        neighborhood_index: 0.18,
        appeal_index: 0.15,
        commercial_middle_class_index: 0.14,
        yield_diversity_index: 0.12,
        cultural_output_index: 0.1,
        culture_index: 0.1,
        science_index: 0.08,
        residential_index: 0.08,
        leisure_tourism_index: 0.06,
        maritime_index: 0.04,
        localist_index: 0.07,
        imperial_core_index: -0.06,
      },
      province: {
        intellectual_index: 0.27,
        spiritual_index: 0.22,
        commerce_index: 0.2,
        appeal_index: 0.16,
        minority_religion_share: 0.13,
        economic_diversity_index: 0.13,
        localist_index: 0.07,
        cultural_output_index: 0.09,
        residential_index: 0.07,
        leisure_tourism_index: 0.06,
        maritime_index: 0.05,
        imperial_core_index: -0.06,
        foreign_origin_index: 0.06,
        frontier_index: 0.04,
      },
      national: {
        intellectual_index: 0.25,
        spiritual_index: 0.2,
        commerce_index: 0.18,
        localist_index: 0.15,
        minority_religion_share: 0.12,
        economic_diversity_index: 0.1,
        cultural_output_index: 0.08,
        residential_index: 0.06,
        leisure_tourism_index: 0.05,
        maritime_index: 0.04,
      },
    },
  },
  {
    id: 'white',
    name: 'Solidarity Americana',
    abbreviation: 'SA',
    colorName: 'White',
    color: '#f8fafc',
    ideology: 'American provincial interest, autonomy bloc, regional-interest party',
    coalitionPartners: ['blue', 'orange', 'red', 'purple', 'yellow'],
    // Diaspora base; "natural" American boost lives in voter blocs.
    bias: { county: 0.003, province: 0.003, national: 0.003 },
    affinities: {
      county: {
        commercial_index: 0.035,
        urban_index: 0.025,
        localist_index: 0.018,
        maritime_index: 0.013,
        wilderness_index: 0.013,
      },
      province: {
        commerce_index: 0.025,
        localist_index: 0.02,
        urbanization_index: 0.025,
        connectedness_index: 0.02,
        conquered_index: 0.015,
        maritime_index: 0.015,
        wilderness_index: 0.015,
        foreign_origin_index: 0.025,
        frontier_index: 0.02,
        cross_continental_index: 0.02,
      },
      national: {
        urbanization_index: 0.04,
        commerce_index: 0.03,
        localist_index: 0.03,
        maritime_index: 0.01,
        wilderness_index: 0.008,
      },
    },
  },
  {
    id: 'purple',
    name: 'Lotus Restorationists',
    abbreviation: 'LR',
    colorName: 'Purple',
    color: '#a78bfa',
    ideology: 'Taoist interest, religious-cultural minority, Roman royal restorationism',
    coalitionPartners: ['red', 'blue', 'yellow', 'white', 'orange'],
    // Diaspora base; "natural" Taoist/Roman boost lives in voter blocs.
    bias: { county: 0.013, province: 0.013, national: 0.011 },
    affinities: {
      county: {
        spiritual_index: 0.055,
        faith_index: 0.04,
        religious_minority_index: 0.03,
        urban_index: 0.02,
        commercial_index: 0.015,
        restorationist_index: 0.025,
        wilderness_index: 0.025,
        mountain_index: 0.015,
      },
      province: {
        spiritual_index: 0.045,
        faith_index: 0.04,
        minority_religion_share: 0.03,
        urbanization_index: 0.025,
        connectedness_index: 0.02,
        restorationist_index: 0.025,
        wilderness_index: 0.025,
        mountain_index: 0.015,
        foreign_origin_index: 0.02,
      },
      national: {
        restorationist_index: 0.16,
        spiritual_index: 0.1,
        urbanization_index: 0.04,
        wilderness_index: 0.018,
        mountain_index: 0.015,
      },
    },
  },
  {
    id: 'green',
    name: 'Green Party',
    abbreviation: 'GP',
    colorName: 'Green',
    color: '#22c55e',
    ideology: 'Environmental conservation, natural preservation, ecological sustainability',
    coalitionPartners: ['blue', 'orange', 'purple', 'red', 'yellow'],
    bias: { county: 0.017, province: 0.02, national: 0.017 },
    affinities: {
      county: {
        appeal_index: 0.14,
        wilderness_index: 0.11,
        rainforest_index: 0.1,
        mountain_index: 0.07,
        coastal_index: 0.06,
        leisure_tourism_index: 0.09,
        protected_marine_index: 0.06,
        maritime_index: 0.05,
        offshore_development_index: 0.05,
        industrial_index: -0.05,
        urban_index: -0.04,
        pollution_index: -0.025,
      },
      province: {
        appeal_index: 0.12,
        wilderness_index: 0.09,
        rainforest_index: 0.09,
        mountain_index: 0.06,
        coastal_index: 0.05,
        leisure_tourism_index: 0.08,
        protected_marine_index: 0.06,
        maritime_index: 0.04,
        offshore_development_index: 0.04,
        cross_continental_index: 0.03,
        industrial_index: -0.04,
        urbanization_index: -0.03,
        pollution_index: -0.02,
      },
      national: {
        appeal_index: 0.14,
        wilderness_index: 0.12,
        rainforest_index: 0.1,
        coastal_index: 0.08,
        leisure_tourism_index: 0.08,
        protected_marine_index: 0.06,
        offshore_development_index: 0.05,
        industrial_index: -0.04,
        urbanization_index: -0.03,
        pollution_index: -0.02,
      },
    },
  },
]
